# Generated by Django 5.2.16 on 2026-09-21 08:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('liturgija', '0002_initial'),
        ('pastoral', '0002_initial'),
        ('zupa_vjernici', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationProgramYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('is_active', models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('public_identifier', models.CharField(default=uuid.uuid4, help_text='Identifikator koji koriste postojeći URL-ovi i korisničko sučelje.', max_length=160, verbose_name='Stabilni identifikator')),
                ('program_type', models.CharField(choices=[('first_communion', 'Prva pričest'), ('confirmation', 'Krizma')], db_index=True, max_length=24, verbose_name='Vrsta priprave')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Godina')),
                ('group_name', models.CharField(blank=True, max_length=160, verbose_name='Naziv skupine')),
                ('ceremony_date', models.DateField(blank=True, null=True, verbose_name='Datum slavlja')),
                ('celebrant_name', models.CharField(blank=True, max_length=200, verbose_name='Slavitelj')),
                ('contribution_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zajednički prilog')),
                ('contribution_paid', models.BooleanField(default=False, verbose_name='Prilog evidentiran')),
                ('contribution_paid_at', models.DateField(blank=True, null=True, verbose_name='Datum evidencije priloga')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formation_program_years', to='pastoral.parish', verbose_name='Župa')),
            ],
            options={
                'verbose_name': 'Godina sakramentalne priprave',
                'verbose_name_plural': 'Godine sakramentalne priprave',
                'db_table': 'pastoral_formationprogramyear',
                'ordering': ('program_type', '-year'),
            },
        ),
        migrations.CreateModel(
            name='SacramentalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('public_identifier', models.CharField(blank=True, help_text='Stabilni identifikator koji koriste URL-ovi i korisničko sučelje.', max_length=160, verbose_name='Stabilni identifikator')),
                ('event_type', models.CharField(choices=[('baptism', 'Krštenje'), ('first_communion', 'Prva pričest'), ('confirmation', 'Krizma'), ('marriage', 'Vjenčanje'), ('anointing', 'Pomazanje'), ('funeral', 'Sprovod')], db_index=True, max_length=24, verbose_name='Vrsta sakramenta')),
                ('event_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Datum')),
                ('place_name', models.CharField(blank=True, max_length=200, verbose_name='Mjesto')),
                ('minister_name', models.CharField(blank=True, max_length=200, verbose_name='Povijesni naziv služitelja')),
                ('canonical_tradition', models.CharField(choices=[('latin', 'Latinska'), ('eastern', 'Istočna'), ('unconfirmed', 'Nepotvrđeno')], default='unconfirmed', max_length=16, verbose_name='Kanonska tradicija')),
                ('status', models.CharField(choices=[('draft', 'Nacrt'), ('confirmed', 'Potvrđeno'), ('locked', 'Zaključano'), ('corrected', 'Ispravljeno'), ('cancelled', 'Poništeno'), ('legacy_imported', 'Uvezeno iz postojećeg sustava')], db_index=True, default='draft', max_length=24, verbose_name='Status')),
                ('source', models.CharField(choices=[('manual', 'Ručni unos'), ('public_submission', 'Javna prijava'), ('legacy_import', 'Postojeći sustav')], db_index=True, default='manual', max_length=24, verbose_name='Izvor')),
                ('celebrating_parish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='celebrated_sacramental_events', to='pastoral.parish', verbose_name='Župa slavlja')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_sacramental_events', to=settings.AUTH_USER_MODEL, verbose_name='Kreirao')),
                ('liturgical_tradition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sacramental_events', to='liturgija.liturgicaltradition', verbose_name='Liturgijska tradicija')),
                ('minister', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ministered_sacramental_events', to=settings.AUTH_USER_MODEL, verbose_name='Služitelj')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sacramental_events', to='pastoral.parish', verbose_name='Župa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_sacramental_events', to=settings.AUTH_USER_MODEL, verbose_name='Ažurirao')),
            ],
            options={
                'verbose_name': 'Sakramentalni događaj',
                'verbose_name_plural': 'Sakramentalni događaji',
                'db_table': 'pastoral_sacramentalevent',
                'ordering': ('-event_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='MarriageDetails',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('couple_display_name', models.CharField(max_length=320, verbose_name='Mladenci')),
                ('contact', models.CharField(blank=True, max_length=160, verbose_name='Kontakt')),
                ('preparatory_sessions', models.PositiveSmallIntegerField(default=0, verbose_name='Broj susreta priprave')),
                ('documents_complete', models.BooleanField(default=False, verbose_name='Dokumenti potpuni')),
                ('witnesses_name', models.CharField(blank=True, max_length=400, verbose_name='Svjedoci')),
                ('groom_witness_name', models.CharField(blank=True, max_length=220, verbose_name='Svjedok zaručnika')),
                ('bride_witness_name', models.CharField(blank=True, max_length=220, verbose_name='Svjedok zaručnice')),
                ('operational_status', models.CharField(db_index=True, default='planirano', max_length=40, verbose_name='Operativni status')),
                ('stipend', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stipendij')),
                ('stipend_paid', models.BooleanField(default=False, verbose_name='Stipendij evidentiran')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='marriage_details', to='sakramenti.sacramentalevent', verbose_name='Vjenčanje')),
            ],
            options={
                'verbose_name': 'Podaci o vjenčanju',
                'verbose_name_plural': 'Podaci o vjenčanjima',
                'db_table': 'pastoral_marriagedetails',
            },
        ),
        migrations.CreateModel(
            name='FuneralDetails',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Datum smrti')),
                ('cemetery_location', models.CharField(blank=True, max_length=240, verbose_name='Adresa / lokacija groblja')),
                ('family_contact', models.CharField(blank=True, max_length=240, verbose_name='Kontakt obitelji')),
                ('mass_planned', models.BooleanField(default=False, verbose_name='Misa zadušnica planirana')),
                ('mass_date', models.DateField(blank=True, null=True, verbose_name='Datum mise zadušnice')),
                ('mass_time', models.TimeField(blank=True, null=True, verbose_name='Vrijeme mise zadušnice')),
                ('operational_status', models.CharField(db_index=True, default='planirano', max_length=40, verbose_name='Operativni status')),
                ('stipend', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stipendij')),
                ('stipend_paid', models.BooleanField(default=False, verbose_name='Stipendij evidentiran')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='funeral_details', to='sakramenti.sacramentalevent', verbose_name='Pogreb')),
            ],
            options={
                'verbose_name': 'Podaci o pogrebu',
                'verbose_name_plural': 'Podaci o pogrebima',
                'db_table': 'pastoral_funeraldetails',
            },
        ),
        migrations.CreateModel(
            name='FormationCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('public_identifier', models.CharField(max_length=160, verbose_name='Stabilni identifikator')),
                ('historical_name', models.CharField(max_length=220, verbose_name='Ime i prezime')),
                ('given_names', models.CharField(blank=True, max_length=160, verbose_name='Ime / imena')),
                ('surname', models.CharField(blank=True, max_length=160, verbose_name='Prezime')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Datum rođenja')),
                ('school_name', models.CharField(blank=True, max_length=200, verbose_name='Škola')),
                ('school_class', models.CharField(blank=True, max_length=40, verbose_name='Razred')),
                ('group_name', models.CharField(blank=True, max_length=80, verbose_name='Skupina')),
                ('parents_name', models.CharField(blank=True, max_length=300, verbose_name='Roditelji')),
                ('sponsor_name', models.CharField(blank=True, max_length=220, verbose_name='Kum / kuma')),
                ('baptism_date', models.DateField(blank=True, null=True, verbose_name='Datum krštenja')),
                ('operational_status', models.CharField(default='upis', max_length=40, verbose_name='Status')),
                ('contribution_paid', models.BooleanField(default=False, verbose_name='Prilog evidentiran')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formation_candidates', to='zupa_vjernici.person', verbose_name='Osoba')),
                ('program_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='sakramenti.formationprogramyear', verbose_name='Godina priprave')),
                ('sacramental_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formation_candidate', to='sakramenti.sacramentalevent', verbose_name='Potvrđeni sakramentalni događaj')),
            ],
            options={
                'verbose_name': 'Kandidat sakramentalne priprave',
                'verbose_name_plural': 'Kandidati sakramentalne priprave',
                'db_table': 'pastoral_formationcandidate',
                'ordering': ('historical_name',),
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('role', models.CharField(choices=[('recipient', 'Primatelj'), ('parent', 'Roditelj'), ('godparent', 'Kum / kuma'), ('sponsor', 'Kum / kuma (krizma)'), ('spouse', 'Zaručnik / zaručnica'), ('witness', 'Svjedok')], db_index=True, max_length=20, verbose_name='Uloga')),
                ('historical_name', models.CharField(blank=True, help_text='Čuva izvorni tekst kada osobe nije sigurno automatski razdvojiti.', max_length=300, verbose_name='Povijesni zapis imena')),
                ('snapshot_given_names', models.CharField(blank=True, max_length=160, verbose_name='Ime u trenutku sakramenta')),
                ('snapshot_surname', models.CharField(blank=True, max_length=160, verbose_name='Prezime u trenutku sakramenta')),
                ('snapshot_sex', models.CharField(blank=True, max_length=12, verbose_name='Spol u trenutku sakramenta')),
                ('snapshot_date_of_birth', models.DateField(blank=True, null=True, verbose_name='Datum rođenja u trenutku sakramenta')),
                ('snapshot_place_of_birth', models.CharField(blank=True, max_length=180, verbose_name='Mjesto rođenja u trenutku sakramenta')),
                ('parent_side', models.CharField(blank=True, max_length=12, verbose_name='Strana roditelja')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Redoslijed prikaza')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sacramental_event_participants', to='pastoral.parish', verbose_name='Župa')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sacramental_participations', to='zupa_vjernici.person', verbose_name='Osoba')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='sakramenti.sacramentalevent', verbose_name='Događaj')),
            ],
            options={
                'verbose_name': 'Sudionik sakramentalnog događaja',
                'verbose_name_plural': 'Sudionici sakramentalnih događaja',
                'db_table': 'pastoral_eventparticipant',
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BaptismDetails',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('godparent_certificate_received', models.BooleanField(default=False, verbose_name='Zaprimljena potvrda za kuma')),
                ('operational_status', models.CharField(db_index=True, default='upis', max_length=40, verbose_name='Operativni status')),
                ('stipend', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prilog')),
                ('stipend_paid', models.BooleanField(default=False, verbose_name='Prilog evidentiran')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='baptism_details', to='sakramenti.sacramentalevent', verbose_name='Krštenje')),
            ],
            options={
                'verbose_name': 'Podaci o krštenju',
                'verbose_name_plural': 'Podaci o krštenjima',
                'db_table': 'pastoral_baptismdetails',
            },
        ),
        migrations.CreateModel(
            name='AnointingDetails',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('scheduled_time', models.TimeField(blank=True, null=True, verbose_name='Vrijeme')),
                ('address', models.CharField(blank=True, max_length=240, verbose_name='Adresa / ustanova')),
                ('location', models.CharField(blank=True, max_length=240, verbose_name='Detalj lokacije')),
                ('contact', models.CharField(blank=True, max_length=240, verbose_name='Kontakt')),
                ('notes', models.TextField(blank=True, verbose_name='Napomena')),
                ('operational_status', models.CharField(db_index=True, default='planirano', max_length=40, verbose_name='Operativni status')),
                ('completed', models.BooleanField(default=False, verbose_name='Obavljeno')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='anointing_details', to='sakramenti.sacramentalevent', verbose_name='Pomazanje')),
            ],
            options={
                'verbose_name': 'Podaci o pomazanju',
                'verbose_name_plural': 'Podaci o pomazanjima',
                'db_table': 'pastoral_anointingdetails',
            },
        ),
        migrations.AddConstraint(
            model_name='formationprogramyear',
            constraint=models.UniqueConstraint(fields=('parish', 'program_type', 'year'), name='unique_formation_program_year'),
        ),
        migrations.AddConstraint(
            model_name='formationprogramyear',
            constraint=models.UniqueConstraint(fields=('parish', 'program_type', 'public_identifier'), name='unique_formation_program_identifier'),
        ),
        migrations.AddIndex(
            model_name='sacramentalevent',
            index=models.Index(fields=['parish', 'event_type', 'event_date'], name='event_parish_type_date'),
        ),
        migrations.AddIndex(
            model_name='sacramentalevent',
            index=models.Index(fields=['parish', 'status'], name='event_parish_status'),
        ),
        migrations.AddConstraint(
            model_name='sacramentalevent',
            constraint=models.UniqueConstraint(condition=models.Q(('public_identifier', ''), _negated=True), fields=('parish', 'event_type', 'public_identifier'), name='unique_event_public_identifier'),
        ),
        migrations.AddConstraint(
            model_name='formationcandidate',
            constraint=models.UniqueConstraint(fields=('program_year', 'public_identifier'), name='unique_candidate_in_program_year'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['parish', 'role'], name='participant_parish_role'),
        ),
        migrations.AddConstraint(
            model_name='eventparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('person__isnull', False), models.Q(('historical_name', ''), _negated=True), _connector='OR'), name='participant_has_person_or_name'),
        ),
    ]
