# Generated by Django 5.2.16 on 2026-09-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakramenti', '0001_move_domain_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='anointingdetails',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='anointingdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='anointingdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AddField(
            model_name='baptismdetails',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='baptismdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='baptismdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='parent_side',
            field=models.CharField(blank=True, max_length=12, verbose_name='Strana roditelja'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='snapshot_date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Datum rođenja u trenutku sakramenta'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='snapshot_given_names',
            field=models.CharField(blank=True, max_length=160, verbose_name='Ime u trenutku sakramenta'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='snapshot_place_of_birth',
            field=models.CharField(blank=True, max_length=180, verbose_name='Mjesto rođenja u trenutku sakramenta'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='snapshot_sex',
            field=models.CharField(blank=True, max_length=12, verbose_name='Spol u trenutku sakramenta'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='snapshot_surname',
            field=models.CharField(blank=True, max_length=160, verbose_name='Prezime u trenutku sakramenta'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AddField(
            model_name='formationcandidate',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='formationprogramyear',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='formationprogramyear',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno'),
        ),
        migrations.AddField(
            model_name='formationprogramyear',
            name='unified_key',
            field=models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ'),
        ),
        migrations.AddField(
            model_name='funeraldetails',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='funeraldetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='funeraldetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AddField(
            model_name='marriagedetails',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='marriagedetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='marriagedetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AddField(
            model_name='sacramentalevent',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AlterField(
            model_name='anointingdetails',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='baptismdetails',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='role',
            field=models.CharField(choices=[('recipient', 'Primatelj'), ('parent', 'Roditelj'), ('godparent', 'Kum / kuma'), ('sponsor', 'Kum / kuma (krizma)'), ('spouse', 'Zaručnik / zaručnica'), ('witness', 'Svjedok')], db_index=True, max_length=20, verbose_name='Uloga'),
        ),
        migrations.AlterField(
            model_name='formationcandidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='formationprogramyear',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='funeraldetails',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marriagedetails',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sacramentalevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
    ]
