# Generated by Django 5.2.16

import uuid
from django.db import migrations, models

PLATFORM_COLOR_VALUE = (
    '{"bgColor": "#f5f3f8", "accentColor": "#9a8fb8", '
    '"colorScheme": "light", "customTheme": false, '
    '"primaryColor": "#4a3d6b", "themePresetId": "advent", '
    '"bgPatternColor": "#ebe8f0"}'
)


def seed_platform_color(apps, schema_editor):
    Settings = apps.get_model('core', 'Settings')
    Settings.objects.get_or_create(
        name='PlatformColor',
        defaults={
            'id': uuid.uuid4(),
            'unified_key': 'PlatformColor',
            'is_active': True,
            'value': PLATFORM_COLOR_VALUE,
            'description': 'Boje i način prikaza sučelja ovog tenanta.',
        },
    )


def unseed_platform_color(apps, schema_editor):
    Settings = apps.get_model('core', 'Settings')
    Settings.objects.filter(name='PlatformColor').delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('is_active', models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Postavka',
                'verbose_name_plural': 'Settings',
                'db_table': 'application_settings',
                'ordering': ('name',),
            },
        ),
        migrations.RunPython(seed_platform_color, unseed_platform_color),
    ]
