"""Konfiguracija župnog listića (bivši zupni_listic_config.json)."""
from __future__ import annotations

ZUPNI_LISTIC_CONFIG = {'blockTypes': {'header': {'label': 'Zaglavlje',
                           'desc': 'Naziv župe, tjedan, župnik — automatski iz '
                                   'postavki',
                           'auto': True,
                           'fixed': True},
                'mass_schedule': {'label': 'Raspored misa',
                                  'desc': 'Automatski iz modula Mise',
                                  'auto': True},
                'nakane': {'label': 'Molitvene nakane',
                           'desc': 'Automatski iz kalendara nakana za tjedan',
                           'auto': True},
                'announcements': {'label': 'Obavijesti župe',
                                  'desc': 'Upišite obavijesti koje želite objaviti u '
                                          'ovom izdanju',
                                  'auto': False},
                'custom_text': {'label': 'Slobodni tekst',
                                'desc': 'Naslov i oblikovani tekst',
                                'auto': False},
                'sacraments': {'label': 'Sakramenti i događaji',
                               'desc': 'Krštenja, vjenčanja, pogrebi, događaji',
                               'auto': True},
                'contact': {'label': 'Kontakt ureda',
                            'desc': 'Telefon, e-mail i adresa župe',
                            'auto': True},
                'footer': {'label': 'Podnožje',
                           'desc': 'Kratka oblikovana napomena na dnu listića',
                           'auto': False,
                           'fixed': True}},
 'defaultLayout': {'blocks': [{'id': 'blk_hdr', 'type': 'header', 'enabled': True},
                              {'id': 'blk_ms',
                               'type': 'mass_schedule',
                               'enabled': True,
                               'title': 'Raspored sv. misa'},
                              {'id': 'blk_nk',
                               'type': 'nakane',
                               'enabled': True,
                               'title': 'Molitvene nakane'},
                              {'id': 'blk_ob',
                               'type': 'announcements',
                               'enabled': True,
                               'title': 'Obavijesti župe'},
                              {'id': 'blk_kt',
                               'type': 'custom_text',
                               'enabled': True,
                               'title': 'Pobožnosti',
                               'body': ''},
                              {'id': 'blk_sk',
                               'type': 'sacraments',
                               'enabled': True,
                               'title': 'Sakramenti i događaji'},
                              {'id': 'blk_ku',
                               'type': 'contact',
                               'enabled': True,
                               'title': 'Župni ured'},
                              {'id': 'blk_ft',
                               'type': 'footer',
                               'enabled': True,
                               'title': '',
                               'body': 'Župni listić — izdanje za župljane.'}],
                   'updatedAt': None},
 'defaultTemplate': {'fileName': 'zupni-listic-zadani.html',
                     'updatedAt': None,
                     'html': ''},
 'fieldLabels': {'biskupija': 'Biskupija / nadbiskupija',
                 'zupa': 'Naziv župe',
                 'grad': 'Mjesto',
                 'zupnik': 'Župnik',
                 'tjedan_od': 'Tjedan od',
                 'tjedan_do': 'Tjedan do',
                 'liturgijska_boja': 'Liturgijska boja',
                 'misni_raspored': 'Raspored misa',
                 'nakane_tjedan': 'Nakane (tjedan)',
                 'obavijesti_zupe': 'Obavijesti župe',
                 'kateheza_pobožnosti': 'Pobožnosti',
                 'sakramenti_dogadaji': 'Sakramenti i događaji',
                 'kontakt_ured': 'Kontakt župnog ureda',
                 'napomena_listica': 'Napomena na listiću',
                 'datum_izdavanja': 'Datum izdavanja'}}
