# Generated by Django 5.2.16 on 2026-08-03 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pastoral', '0004_alter_parish_tenant_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParishWebsite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('provisioning', 'Izrada u tijeku'), ('draft', 'Skica spremna'), ('live', 'Objavljeno'), ('suspended', 'Privremeno obustavljeno'), ('archived', 'Arhivirano')], db_index=True, default='provisioning', max_length=20)),
                ('subdomain', models.SlugField(unique=True)),
                ('custom_domain', models.CharField(blank=True, max_length=253)),
                ('template_key', models.CharField(choices=[('classic', 'Klasični'), ('warm', 'Topli pastoralni'), ('modern', 'Suvremeni')], default='classic', max_length=24)),
                ('site_name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=240)),
                ('primary_color', models.CharField(default='#5c2e3a', max_length=7)),
                ('accent_color', models.CharField(default='#b8922a', max_length=7)),
                ('enabled_sections', models.JSONField(blank=True, default=list)),
                ('activated_at', models.DateTimeField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parish', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='public_website', to='pastoral.parish')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_public_websites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Javna web-stranica župe',
                'verbose_name_plural': 'Javne web-stranice župa',
                'ordering': ('parish',),
            },
        ),
        migrations.CreateModel(
            name='WebsiteBuild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('initial', 'Početna izrada'), ('preview', 'Izrada pregleda'), ('publish', 'Objava')], max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Zakazano'), ('running', 'U tijeku'), ('succeeded', 'Dovršeno'), ('failed', 'Neuspješno')], db_index=True, max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_website_builds', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='builds', to='public_site.parishwebsite')),
            ],
            options={
                'verbose_name': 'Izrada javne web-stranice',
                'verbose_name_plural': 'Izrade javnih web-stranica',
                'ordering': ('-queued_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='public_site_build_progress_range')],
            },
        ),
    ]
