# Generated by Django 5.2.16 on 2026-08-03

import django.db.models.deletion
import public_site.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0003_seed_existing_website_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParishWebsiteMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('hero', 'Naslovna fotografija'), ('gallery', 'Galerija')], db_index=True, max_length=16)),
                ('image', models.ImageField(max_length=255, upload_to=public_site.models.website_media_upload_to)),
                ('alt_text', models.CharField(max_length=240)),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('file_size', models.PositiveIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_public_website_media', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='public_site.parishwebsite')),
            ],
            options={
                'verbose_name': 'Fotografija javne web-stranice',
                'verbose_name_plural': 'Fotografije javnih web-stranica',
                'ordering': ('kind', 'sort_order', 'created_at'),
            },
        ),
    ]
