# Generated by Django 5.2.16 on 2026-09-21 08:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralRegisterEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('public_identifier', models.CharField(max_length=160, verbose_name='Stabilni identifikator')),
                ('registry_reference', models.CharField(blank=True, max_length=100, verbose_name='Matični broj')),
                ('subject_name', models.CharField(max_length=240, verbose_name='Osoba / zapis')),
                ('record_date', models.DateField(verbose_name='Datum zapisa')),
                ('place', models.CharField(blank=True, max_length=240, verbose_name='Mjesto / napomena')),
                ('responsible_name', models.CharField(blank=True, max_length=200, verbose_name='Odgovorna osoba')),
                ('operational_status', models.CharField(db_index=True, default='upisano', max_length=60, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Opći zapis matične knjige',
                'verbose_name_plural': 'Opći zapisi matične knjige',
                'db_table': 'pastoral_generalregisterentry',
                'ordering': ('register_book_year', 'record_date', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='RegisterBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('is_active', models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('public_identifier', models.CharField(blank=True, max_length=160, verbose_name='Stabilni identifikator')),
                ('title', models.CharField(max_length=220, verbose_name='Naziv')),
                ('registry_type', models.CharField(choices=[('krštenja', 'Krštenja'), ('vjenčanja', 'Vjenčanja'), ('umrli', 'Umrli'), ('krizma', 'Krizma'), ('ostalo', 'Ostalo')], default='ostalo', max_length=20, verbose_name='Vrsta knjige')),
                ('volume', models.CharField(blank=True, max_length=80, verbose_name='Svezak')),
                ('year_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Od godine')),
                ('year_until', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Do godine')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Mjesto čuvanja')),
                ('custodian', models.CharField(blank=True, max_length=200, verbose_name='Odgovorna osoba')),
                ('status', models.CharField(choices=[('draft', 'Nacrt'), ('active', 'Aktivna'), ('locked', 'Zaključana'), ('archived', 'Arhivirana')], db_index=True, default='draft', max_length=12, verbose_name='Status')),
                ('operational_status', models.CharField(blank=True, max_length=80, verbose_name='Opis statusa')),
                ('last_entry_date', models.DateField(blank=True, null=True, verbose_name='Zadnji unos')),
                ('last_entry_reference', models.CharField(blank=True, max_length=80, verbose_name='Zadnji broj')),
                ('notes', models.TextField(blank=True, verbose_name='Napomena')),
            ],
            options={
                'verbose_name': 'Matična knjiga',
                'verbose_name_plural': 'Matične knjige',
                'db_table': 'pastoral_registerbook',
                'ordering': ('parish', 'title'),
            },
        ),
        migrations.CreateModel(
            name='RegisterBookYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('is_active', models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Godina')),
                ('status', models.CharField(choices=[('open', 'Otvorena'), ('locked', 'Zaključana'), ('archived', 'Arhivirana')], default='open', max_length=12, verbose_name='Status')),
                ('next_entry_number', models.PositiveIntegerField(default=1, verbose_name='Sljedeći redni broj')),
            ],
            options={
                'verbose_name': 'Godina matične knjige',
                'verbose_name_plural': 'Godine matičnih knjiga',
                'db_table': 'pastoral_registerbookyear',
                'ordering': ('register_book', '-year'),
            },
        ),
        migrations.CreateModel(
            name='RegisterEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('entry_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Redni broj')),
                ('entry_reference', models.CharField(blank=True, max_length=100, verbose_name='Izvorna oznaka zapisa')),
                ('page_number', models.CharField(blank=True, max_length=40, verbose_name='Stranica')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Datum upisa')),
                ('status', models.CharField(choices=[('draft', 'Nacrt'), ('confirmed', 'Potvrđeno'), ('locked', 'Zaključano'), ('corrected', 'Ispravljeno'), ('cancelled', 'Poništeno'), ('legacy_imported', 'Uvezeno iz postojećeg sustava')], db_index=True, default='draft', max_length=24, verbose_name='Status')),
                ('custom_values', models.JSONField(blank=True, default=dict, verbose_name='Dodatna polja predloška')),
                ('correction_reason', models.TextField(blank=True, verbose_name='Razlog ispravka')),
            ],
            options={
                'verbose_name': 'Zapis matične knjige',
                'verbose_name_plural': 'Zapisi matičnih knjiga',
                'db_table': 'pastoral_registerentry',
                'ordering': ('register_book_year', 'entry_number', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='RegisterTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('is_active', models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='Stabilni kod')),
                ('event_type', models.CharField(choices=[('baptism', 'Krštenje'), ('first_communion', 'Prva pričest'), ('confirmation', 'Krizma'), ('marriage', 'Vjenčanje'), ('anointing', 'Pomazanje'), ('funeral', 'Sprovod')], max_length=24, verbose_name='Vrsta sakramenta')),
                ('name', models.CharField(max_length=220, verbose_name='Naziv')),
                ('owner_scope', models.CharField(choices=[('system', 'Sustav'), ('church', 'Kanonska tradicija'), ('jurisdiction', 'Crkvena jurisdikcija')], default='system', max_length=16, verbose_name='Vlasnik')),
                ('canonical_tradition', models.CharField(blank=True, choices=[('latin', 'Latinska'), ('eastern', 'Istočna')], db_index=True, help_text='Latinska ili istočna (Križevačka eparhija), ako predložak nije opći.', max_length=16, verbose_name='Kanonska tradicija')),
                ('is_official', models.BooleanField(default=False, verbose_name='Službeni obrazac')),
            ],
            options={
                'verbose_name': 'Predložak matične knjige',
                'verbose_name_plural': 'Predlošci matičnih knjiga',
                'db_table': 'pastoral_registertemplate',
                'ordering': ('event_type', 'name'),
            },
        ),
        migrations.CreateModel(
            name='RegisterTemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('is_active', models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('version_number', models.PositiveSmallIntegerField(verbose_name='Verzija')),
                ('status', models.CharField(choices=[('draft', 'Nacrt'), ('published', 'Objavljeno'), ('retired', 'Povučeno')], default='draft', max_length=12, verbose_name='Status')),
                ('field_schema', models.JSONField(blank=True, default=list, verbose_name='Definicije polja')),
                ('validation_schema', models.JSONField(blank=True, default=dict, verbose_name='Pravila validacije')),
                ('terminology', models.JSONField(blank=True, default=dict, verbose_name='Terminologija')),
                ('print_configuration', models.JSONField(blank=True, default=dict, verbose_name='Postavke ispisa')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='Vrijedi od')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Objavljeno')),
            ],
            options={
                'verbose_name': 'Verzija predloška matične knjige',
                'verbose_name_plural': 'Verzije predložaka matičnih knjiga',
                'db_table': 'pastoral_registertemplateversion',
                'ordering': ('template', '-version_number'),
            },
        ),
        migrations.CreateModel(
            name='RegistryAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('event_type', models.CharField(db_index=True, max_length=100, verbose_name='Vrsta događaja')),
                ('target_type', models.CharField(blank=True, max_length=100, verbose_name='Vrsta cilja')),
                ('target_id', models.CharField(blank=True, max_length=100, verbose_name='Identifikator cilja')),
                ('outcome', models.CharField(choices=[('success', 'Uspjeh'), ('denied', 'Odbijeno'), ('failure', 'Greška')], db_index=True, default='success', max_length=16, verbose_name='Ishod')),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('changed_fields', models.JSONField(blank=True, default=list, verbose_name='Promijenjena polja')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metapodaci')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vrijeme')),
            ],
            options={
                'verbose_name': 'Audit matične evidencije',
                'verbose_name_plural': 'Audit matične evidencije',
                'db_table': 'pastoral_registryauditevent',
                'ordering': ('-occurred_at',),
            },
        ),
    ]
