# Generated by Django 5.2.16 on 2026-08-21 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.migrations.operations.special import SeparateDatabaseAndState


class Migration(migrations.Migration):

    dependencies = [
        ('isprave', '0001_move_domain_models'),
        ('pastoral', '0028_harden_otp_challenges'),
        ('sakramenti', '0001_move_domain_models'),
        ('zupa_vjernici', '0001_move_domain_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        SeparateDatabaseAndState(
            state_operations=[

                    migrations.AddField(
                        model_name='registerentry',
                        name='event',
                        field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='register_entry', to='sakramenti.sacramentalevent', verbose_name='Događaj'),
                    ),
                    migrations.AddField(
                        model_name='registerentry',
                        name='parish',
                        field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register_entries', to='pastoral.parish', verbose_name='Župa'),
                    ),
                    migrations.AddField(
                        model_name='registerentry',
                        name='previous_entry',
                        field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_entries', to='isprave.registerentry', verbose_name='Prethodni zapis'),
                    ),
                    migrations.AddField(
                        model_name='registerentry',
                        name='register_book_year',
                        field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='isprave.registerbookyear', verbose_name='Godina knjige'),
                    ),
                    migrations.AddField(
                        model_name='registerentry',
                        name='updated_by',
                        field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_register_entries', to=settings.AUTH_USER_MODEL, verbose_name='Ažurirao'),
                    ),
                    migrations.AddField(
                        model_name='registertemplate',
                        name='church_sui_iuris',
                        field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='register_templates', to='zupa_vjernici.churchsuiiuris', verbose_name='Crkva sui iuris'),
                    ),
                    migrations.AddField(
                        model_name='registertemplate',
                        name='ecclesiastical_jurisdiction',
                        field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='register_templates', to='zupa_vjernici.ecclesiasticaljurisdiction', verbose_name='Crkvena jurisdikcija'),
                    ),
                    migrations.AddField(
                        model_name='registertemplateversion',
                        name='published_by',
                        field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_register_template_versions', to=settings.AUTH_USER_MODEL, verbose_name='Objavio'),
                    ),
                    migrations.AddField(
                        model_name='registertemplateversion',
                        name='template',
                        field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='isprave.registertemplate', verbose_name='Predložak'),
                    ),
                    migrations.AddField(
                        model_name='registerentry',
                        name='template_version',
                        field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register_entries', to='isprave.registertemplateversion', verbose_name='Verzija predloška'),
                    ),
                    migrations.AddField(
                        model_name='registerbook',
                        name='template_version',
                        field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='register_books', to='isprave.registertemplateversion', verbose_name='Verzija predloška'),
                    ),
                    migrations.AddField(
                        model_name='registryauditevent',
                        name='actor',
                        field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registry_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Korisnik'),
                    ),
                    migrations.AddField(
                        model_name='registryauditevent',
                        name='parish',
                        field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registry_audit_events', to='pastoral.parish', verbose_name='Župa'),
                    ),
                    migrations.AddConstraint(
                        model_name='registerbookyear',
                        constraint=models.UniqueConstraint(fields=('register_book', 'year'), name='unique_register_book_year'),
                    ),
                    migrations.AddConstraint(
                        model_name='generalregisterentry',
                        constraint=models.UniqueConstraint(fields=('register_book_year', 'public_identifier'), name='unique_general_entry_identifier'),
                    ),
                    migrations.AddConstraint(
                        model_name='registertemplateversion',
                        constraint=models.UniqueConstraint(fields=('template', 'version_number'), name='unique_register_template_version'),
                    ),
                    migrations.AddIndex(
                        model_name='registerentry',
                        index=models.Index(fields=['parish', 'status'], name='entry_parish_status'),
                    ),
                    migrations.AddConstraint(
                        model_name='registerentry',
                        constraint=models.UniqueConstraint(condition=models.Q(('entry_number__isnull', False)), fields=('register_book_year', 'entry_number'), name='unique_number_in_register_book_year'),
                    ),
                    migrations.AddIndex(
                        model_name='registerbook',
                        index=models.Index(fields=['parish', 'status'], name='book_parish_status'),
                    ),
                    migrations.AddConstraint(
                        model_name='registerbook',
                        constraint=models.UniqueConstraint(condition=models.Q(('public_identifier', ''), _negated=True), fields=('parish', 'public_identifier'), name='unique_register_book_public_identifier'),
                    ),
                    migrations.AddIndex(
                        model_name='registryauditevent',
                        index=models.Index(fields=['parish', 'occurred_at'], name='registry_audit_parish_time'),
                    ),
                    migrations.AddIndex(
                        model_name='registryauditevent',
                        index=models.Index(fields=['actor', 'occurred_at'], name='registry_audit_actor_time'),
                    ),
            ],
            database_operations=[],
        ),
    ]
