# Generated by Django 5.2.16 on 2026-09-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isprave', '0002_move_domain_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalregisterentry',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='registerbook',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='registerbook',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno'),
        ),
        migrations.AddField(
            model_name='registerbook',
            name='unified_key',
            field=models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ'),
        ),
        migrations.AddField(
            model_name='registerbookyear',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='registerbookyear',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='registerbookyear',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno'),
        ),
        migrations.AddField(
            model_name='registerbookyear',
            name='unified_key',
            field=models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ'),
        ),
        migrations.AddField(
            model_name='registerbookyear',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AddField(
            model_name='registerentry',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='registertemplate',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='registertemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='registertemplate',
            name='unified_key',
            field=models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ'),
        ),
        migrations.AddField(
            model_name='registertemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AddField(
            model_name='registertemplateversion',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='registertemplateversion',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno'),
        ),
        migrations.AddField(
            model_name='registertemplateversion',
            name='unified_key',
            field=models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ'),
        ),
        migrations.AddField(
            model_name='registryauditevent',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='registryauditevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='registryauditevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AlterField(
            model_name='generalregisterentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='registerbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='registerentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='registertemplate',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno'),
        ),
        migrations.AlterField(
            model_name='registertemplateversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
    ]
