# Generated by Django 5.2.16 on 2026-09-21 08:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pastoral', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('parish', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='finance_settings', serialize=False, to='pastoral.parish')),
                ('lukno_default_amount', models.DecimalField(decimal_places=2, default=0, help_text='Iznos lukna kad obiteljska godina nema vlastiti iznos.', max_digits=10)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktivno')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashbookEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('entry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('entry_type', models.CharField(blank=True, default='ulaz', max_length=20)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('ledger', models.CharField(blank=True, default='crkveni', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(blank=True, max_length=40)),
                ('report_code', models.CharField(blank=True, max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashbook_entries', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('number', models.CharField(blank=True, max_length=64)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payer_name', models.CharField(blank=True, max_length=255)),
                ('payer_address', models.CharField(blank=True, max_length=255)),
                ('payer_oib', models.CharField(blank=True, max_length=32)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('linked_source', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('direction', models.CharField(blank=True, max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
        migrations.CreateModel(
            name='ParishDebt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('direction', models.CharField(blank=True, default='payable', max_length=20)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parish_debts', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
    ]
