# Generated by Django 5.2.16 on 2026-08-21 11:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pastoral', '0031_operational_parish_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('parish', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='finance_settings', serialize=False, to='pastoral.parish')),
                ('lukno_default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashbookEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashbook_entries', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
        migrations.CreateModel(
            name='ParishDebt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parish_debts', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
    ]
