# Generated by Django 5.2.16 on 2026-08-03 11:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pastoral', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diocese',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Biskupija',
                'verbose_name_plural': 'Biskupije',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LicenseGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Na čekanju'), ('active', 'Aktivno'), ('suspended', 'Suspendirano'), ('terminated', 'Prekinuto')], db_index=True, default='pending', max_length=16)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('grace_until', models.DateField()),
                ('plan_code', models.SlugField(default='standard')),
                ('seat_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('terms_version', models.CharField(default='1', max_length=32)),
                ('security_suspended', models.BooleanField(db_index=True, default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_license_grants', to=settings.AUTH_USER_MODEL)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_grants', to='pastoral.parish')),
            ],
            options={
                'verbose_name': 'Licenca',
                'verbose_name_plural': 'Licence',
                'ordering': ('-valid_until', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='LicenseEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField()),
                ('enabled', models.BooleanField(default=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='control_plane.licensegrant')),
            ],
            options={
                'verbose_name': 'Licencno pravo',
                'verbose_name_plural': 'Licencna prava',
                'ordering': ('grant', 'code'),
            },
        ),
        migrations.CreateModel(
            name='LicenseDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('activate', 'Aktivacija'), ('renew', 'Obnova'), ('suspend', 'Suspenzija'), ('reinstate', 'Ponovna aktivacija'), ('terminate', 'Prekid')], max_length=16)),
                ('reason', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_decisions', to=settings.AUTH_USER_MODEL)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='control_plane.licensegrant')),
            ],
            options={
                'verbose_name': 'Odluka o licenci',
                'verbose_name_plural': 'Odluke o licencama',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='ManualPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('value_date', models.DateField()),
                ('payer_name', models.CharField(max_length=200)),
                ('bank_reference', models.CharField(blank=True, max_length=140)),
                ('statement_reference', models.CharField(blank=True, max_length=255)),
                ('coverage_from', models.DateField(blank=True, null=True)),
                ('coverage_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('recorded', 'Evidentirano'), ('verified', 'Provjereno'), ('rejected', 'Odbijeno'), ('reversed', 'Stornirano')], db_index=True, default='recorded', max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_payments', to='pastoral.parish')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_manual_payments', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_manual_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ručna uplata',
                'verbose_name_plural': 'Ručne uplate',
                'ordering': ('-value_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ParishMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('zupnik', 'Župnik'), ('vikar', 'Župnik suradnik / vikar'), ('upravitelj', 'Župni upravitelj'), ('ured', 'Župni ured'), ('financije', 'Financije'), ('revizor', 'Revizor'), ('biskupija', 'Biskupijski preglednik')], max_length=24)),
                ('status', models.CharField(choices=[('active', 'Aktivno'), ('suspended', 'Suspendirano'), ('revoked', 'Opozvano')], db_index=True, default='active', max_length=16)),
                ('permission_set', models.JSONField(blank=True, default=dict)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_parish_memberships', to=settings.AUTH_USER_MODEL)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='pastoral.parish')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_parish_memberships', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parish_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Članstvo u župi',
                'verbose_name_plural': 'Članstva u župama',
                'ordering': ('parish', 'user__email'),
            },
        ),
        migrations.CreateModel(
            name='TenantDatabase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.SlugField(unique=True)),
                ('provider', models.CharField(default='postgresql', max_length=40)),
                ('deployment_stamp', models.CharField(blank=True, max_length=80)),
                ('database_name', models.CharField(blank=True, max_length=128)),
                ('resource_id', models.CharField(blank=True, max_length=255)),
                ('secret_ref', models.CharField(blank=True, help_text='Referenca na secrets manager; nikada lozinka ili connection string.', max_length=255)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('planned', 'Planirano'), ('provisioning', 'Provisioning'), ('ready', 'Spremno'), ('maintenance', 'Održavanje'), ('failed', 'Greška'), ('retired', 'Umirovljeno')], db_index=True, default='planned', max_length=20)),
                ('schema_version', models.CharField(blank=True, max_length=64)),
                ('last_migrated_at', models.DateTimeField(blank=True, null=True)),
                ('last_backup_at', models.DateTimeField(blank=True, null=True)),
                ('last_restore_test_at', models.DateTimeField(blank=True, null=True)),
                ('parish', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_database', to='pastoral.parish')),
            ],
            options={
                'verbose_name': 'Tenant baza',
                'verbose_name_plural': 'Tenant baze',
                'ordering': ('alias',),
            },
        ),
        migrations.CreateModel(
            name='ControlPlaneAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('outcome', models.CharField(choices=[('success', 'Uspjeh'), ('denied', 'Odbijeno'), ('failure', 'Greška')], db_index=True, default='success', max_length=16)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='control_audit_events', to=settings.AUTH_USER_MODEL)),
                ('parish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='control_audit_events', to='pastoral.parish')),
            ],
            options={
                'verbose_name': 'Control-plane audit događaj',
                'verbose_name_plural': 'Control-plane audit događaji',
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['parish', 'occurred_at'], name='control_audit_parish_time'), models.Index(fields=['actor', 'occurred_at'], name='control_audit_actor_time')],
            },
        ),
        migrations.AddIndex(
            model_name='licensegrant',
            index=models.Index(fields=['parish', 'status', 'valid_until'], name='control_license_lookup'),
        ),
        migrations.AddConstraint(
            model_name='licensegrant',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__gte', models.F('valid_from'))), name='control_license_valid_period'),
        ),
        migrations.AddConstraint(
            model_name='licensegrant',
            constraint=models.CheckConstraint(condition=models.Q(('grace_until__gte', models.F('valid_until'))), name='control_license_grace_period'),
        ),
        migrations.AddConstraint(
            model_name='licenseentitlement',
            constraint=models.UniqueConstraint(fields=('grant', 'code'), name='control_unique_grant_entitlement'),
        ),
        migrations.AddIndex(
            model_name='manualpayment',
            index=models.Index(fields=['parish', 'status', 'value_date'], name='control_payment_lookup'),
        ),
        migrations.AddConstraint(
            model_name='manualpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='control_payment_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='manualpayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('coverage_from__isnull', True), ('coverage_until__isnull', True)), models.Q(('coverage_from__isnull', False), ('coverage_until__gte', models.F('coverage_from')), ('coverage_until__isnull', False)), _connector='OR'), name='control_payment_coverage_period'),
        ),
        migrations.AddIndex(
            model_name='parishmembership',
            index=models.Index(fields=['parish', 'status'], name='control_mem_parish_status'),
        ),
        migrations.AddIndex(
            model_name='parishmembership',
            index=models.Index(fields=['user', 'status'], name='control_mem_user_status'),
        ),
        migrations.AddConstraint(
            model_name='parishmembership',
            constraint=models.UniqueConstraint(fields=('parish', 'user'), name='control_unique_parish_user_membership'),
        ),
        migrations.AddConstraint(
            model_name='parishmembership',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='control_membership_valid_period'),
        ),
    ]
