# Generated by Django 5.2.16 on 2026-09-21 08:23

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pastoral', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcclesiasticalJurisdiction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('is_active', models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='Stabilni kod')),
                ('official_name', models.CharField(max_length=220, verbose_name='Službeni naziv')),
                ('jurisdiction_type', models.CharField(choices=[('diocese', 'Biskupija'), ('archdiocese', 'Nadbiskupija'), ('eparchy', 'Eparhija'), ('archeparchy', 'Arhieparhija'), ('other', 'Drugo')], db_index=True, max_length=20, verbose_name='Vrsta jurisdikcije')),
                ('canonical_tradition', models.CharField(choices=[('latin', 'Latinska'), ('eastern', 'Istočna')], db_index=True, max_length=16, verbose_name='Kanonska tradicija')),
                ('parent_jurisdiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_jurisdictions', to='zupa_vjernici.ecclesiasticaljurisdiction', verbose_name='Nadređena jurisdikcija')),
            ],
            options={
                'verbose_name': 'Crkvena jurisdikcija',
                'verbose_name_plural': 'Crkvene jurisdikcije',
                'db_table': 'pastoral_ecclesiasticaljurisdiction',
                'ordering': ('official_name',),
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('date_from', models.DateField(default=datetime.date.today, verbose_name='Vrijedi od')),
                ('date_to', models.DateField(db_index=True, default=datetime.date(9999, 12, 31), verbose_name='Vrijedi do')),
                ('is_active', models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno')),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('surname', models.CharField(blank=True, max_length=160)),
                ('street_public_identifier', models.CharField(blank=True, max_length=64)),
                ('house_number', models.CharField(blank=True, max_length=32)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(blank=True, default='aktivna', max_length=40)),
                ('preferred_mass', models.CharField(blank=True, max_length=40)),
                ('pastoral_notes', models.TextField(blank=True)),
                ('origin_place', models.CharField(blank=True, max_length=160)),
                ('last_visit_on', models.DateField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to='pastoral.parish')),
            ],
            options={
                'ordering': ['surname', 'public_identifier'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('is_active', models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('given_names', models.CharField(max_length=160, verbose_name='Ime / imena')),
                ('surname', models.CharField(max_length=160, verbose_name='Prezime')),
                ('birth_surname', models.CharField(blank=True, max_length=160, verbose_name='Rođeno prezime')),
                ('sex', models.CharField(choices=[('female', 'Ženski'), ('male', 'Muški')], default='male', max_length=12, verbose_name='Spol')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Datum rođenja')),
                ('place_of_birth', models.CharField(blank=True, max_length=180, verbose_name='Mjesto rođenja')),
                ('normalized_given_names', models.CharField(db_index=True, editable=False, max_length=160)),
                ('normalized_surname', models.CharField(db_index=True, editable=False, max_length=160)),
                ('status', models.CharField(choices=[('active', 'Aktivna'), ('merged', 'Spojena'), ('archived', 'Arhivirana')], db_index=True, default='active', max_length=12, verbose_name='Status')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_as_father', to='zupa_vjernici.person', verbose_name='Otac')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_as_mother', to='zupa_vjernici.person', verbose_name='Majka')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persons', to='pastoral.parish', verbose_name='Župa')),
            ],
            options={
                'verbose_name': 'Osoba',
                'verbose_name_plural': 'Osobe',
                'db_table': 'pastoral_person',
                'ordering': ('surname', 'given_names', 'date_of_birth'),
            },
        ),
        migrations.CreateModel(
            name='HouseholdMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('date_from', models.DateField(default=datetime.date.today, verbose_name='Vrijedi od')),
                ('date_to', models.DateField(db_index=True, default=datetime.date(9999, 12, 31), verbose_name='Vrijedi do')),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('historical_name', models.CharField(blank=True, max_length=160)),
                ('role', models.CharField(blank=True, help_text='Slobodni tekst iz kartona (majka, sin, rođak…).', max_length=80, verbose_name='Odnos u obitelji')),
                ('spouse_side', models.CharField(blank=True, choices=[('', 'Nije bračni karton'), ('husband', 'Muž'), ('wife', 'Žena')], default='', help_text='Označava muža/ženu na kartonu; nije zamjena za sakrament vjenčanja.', max_length=12)),
                ('lives_in_household', models.BooleanField(default=True, help_text='False = rodbina / veza izvan kuće, i dalje Person.')),
                ('is_head', models.BooleanField(default=False)),
                ('recorded_birth_year', models.CharField(blank=True, max_length=20)),
                ('pastoral_roles', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='zupa_vjernici.household')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='household_memberships', to='zupa_vjernici.person')),
            ],
            options={
                'verbose_name': 'Članstvo u kućanstvu',
                'verbose_name_plural': 'Članstva u kućanstvu',
                'ordering': ['sort_order', 'historical_name'],
            },
        ),
        migrations.CreateModel(
            name='ChurchEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('date_from', models.DateField(default=datetime.date.today, verbose_name='Vrijedi od')),
                ('date_to', models.DateField(db_index=True, default=datetime.date(9999, 12, 31), verbose_name='Vrijedi do')),
                ('canonical_tradition', models.CharField(choices=[('latin', 'Latinska'), ('eastern', 'Istočna')], db_index=True, max_length=16, verbose_name='Kanonska tradicija')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Vrijedi od')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Vrijedi do')),
                ('enrollment_basis', models.CharField(blank=True, max_length=200, verbose_name='Temelj pripadnosti')),
                ('decree_reference', models.CharField(blank=True, max_length=200, verbose_name='Referenca dekreta')),
                ('status', models.CharField(choices=[('unconfirmed', 'Nepotvrđeno'), ('confirmed', 'Potvrđeno')], db_index=True, default='unconfirmed', max_length=12, verbose_name='Status')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='church_enrollments', to='pastoral.parish', verbose_name='Župa')),
                ('previous_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='following_enrollments', to='zupa_vjernici.churchenrollment', verbose_name='Prethodna pripadnost')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_church_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Evidentirao')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='church_enrollments', to='zupa_vjernici.person', verbose_name='Osoba')),
            ],
            options={
                'verbose_name': 'Kanonska pripadnost',
                'verbose_name_plural': 'Kanonske pripadnosti',
                'db_table': 'pastoral_churchenrollment',
                'ordering': ('person', '-valid_from', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('date_from', models.DateField(default=datetime.date.today, verbose_name='Vrijedi od')),
                ('date_to', models.DateField(db_index=True, default=datetime.date(9999, 12, 31), verbose_name='Vrijedi do')),
                ('is_active', models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno')),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('zone', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='pastoral.parish')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='household',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='households', to='zupa_vjernici.street'),
        ),
        migrations.CreateModel(
            name='HouseholdContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('year', models.PositiveIntegerField(db_index=True, default=0)),
                ('lukno_paid', models.BooleanField(default=False)),
                ('lukno_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lukno_paid_at', models.DateField(blank=True, null=True)),
                ('church_donation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('donation_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='zupa_vjernici.household')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('household', 'public_identifier')},
            },
        ),
        migrations.CreateModel(
            name='PastoralVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('family_public_identifier', models.CharField(blank=True, max_length=64)),
                ('scheduled_on', models.DateField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('visit_type', models.CharField(blank=True, max_length=80)),
                ('person_name', models.CharField(blank=True, max_length=160)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('priest', models.CharField(blank=True, max_length=160)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('report', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='zupa_vjernici.household')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastoral_visits', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['parish', 'normalized_surname', 'normalized_given_names'], name='person_parish_name_lookup'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['parish', 'date_of_birth'], name='person_parish_birth_lookup'),
        ),
        migrations.AddConstraint(
            model_name='householdmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('date_to', datetime.date(9999, 12, 31))), fields=('household', 'public_identifier'), name='householdmembership_one_current_id'),
        ),
        migrations.AddConstraint(
            model_name='householdmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('date_to', datetime.date(9999, 12, 31)), ('person__isnull', False)), fields=('person',), name='householdmembership_one_current_person'),
        ),
        migrations.AddIndex(
            model_name='churchenrollment',
            index=models.Index(fields=['parish', 'status'], name='enrollment_parish_status'),
        ),
        migrations.AddConstraint(
            model_name='churchenrollment',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_from__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='enrollment_valid_period'),
        ),
        migrations.AddConstraint(
            model_name='churchenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed'), ('valid_until__isnull', True)), fields=('person',), name='one_current_confirmed_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='street',
            constraint=models.UniqueConstraint(condition=models.Q(('date_to', datetime.date(9999, 12, 31))), fields=('parish', 'public_identifier'), name='street_one_current_public_id'),
        ),
        migrations.AddConstraint(
            model_name='household',
            constraint=models.UniqueConstraint(condition=models.Q(('date_to', datetime.date(9999, 12, 31))), fields=('parish', 'public_identifier'), name='household_one_current_public_id'),
        ),
    ]
