# Generated by Django 5.2.16 on 2026-08-21 11:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.migrations.operations.special import SeparateDatabaseAndState


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pastoral', '0028_harden_otp_challenges'),
        ('liturgija', '0001_move_domain_models'),
    ]

    operations = [
        SeparateDatabaseAndState(
            state_operations=[

                    migrations.CreateModel(
                        name='ChurchSuiIuris',
                        fields=[
                            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                            ('code', models.SlugField(max_length=60, unique=True, verbose_name='Stabilni kod')),
                            ('official_name', models.CharField(max_length=200, verbose_name='Službeni naziv')),
                            ('short_name', models.CharField(blank=True, max_length=120, verbose_name='Kratki naziv')),
                            ('canonical_tradition', models.CharField(choices=[('latin', 'Latinska'), ('eastern', 'Istočna')], db_index=True, max_length=16, verbose_name='Kanonska tradicija')),
                            ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktivno')),
                            ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                            ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                            ('default_liturgical_tradition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='churches_sui_iuris', to='liturgija.liturgicaltradition', verbose_name='Zadana liturgijska tradicija')),
                        ],
                        options={
                            'verbose_name': 'Crkva sui iuris',
                            'verbose_name_plural': 'Crkve sui iuris',
                            'db_table': 'pastoral_churchsuiiuris',
                            'ordering': ('official_name',),
                        },
                    ),
                    migrations.CreateModel(
                        name='EcclesiasticalJurisdiction',
                        fields=[
                            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                            ('code', models.SlugField(max_length=80, unique=True, verbose_name='Stabilni kod')),
                            ('official_name', models.CharField(max_length=220, verbose_name='Službeni naziv')),
                            ('jurisdiction_type', models.CharField(choices=[('diocese', 'Biskupija'), ('archdiocese', 'Nadbiskupija'), ('eparchy', 'Eparhija'), ('archeparchy', 'Arhieparhija'), ('other', 'Drugo')], db_index=True, max_length=20, verbose_name='Vrsta jurisdikcije')),
                            ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktivno')),
                            ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                            ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                            ('church_sui_iuris', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jurisdictions', to='zupa_vjernici.churchsuiiuris', verbose_name='Crkva sui iuris')),
                            ('parent_jurisdiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_jurisdictions', to='zupa_vjernici.ecclesiasticaljurisdiction', verbose_name='Nadređena jurisdikcija')),
                        ],
                        options={
                            'verbose_name': 'Crkvena jurisdikcija',
                            'verbose_name_plural': 'Crkvene jurisdikcije',
                            'db_table': 'pastoral_ecclesiasticaljurisdiction',
                            'ordering': ('official_name',),
                        },
                    ),
                    migrations.CreateModel(
                        name='Person',
                        fields=[
                            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                            ('given_names', models.CharField(max_length=160, verbose_name='Ime / imena')),
                            ('surname', models.CharField(max_length=160, verbose_name='Prezime')),
                            ('birth_surname', models.CharField(blank=True, max_length=160, verbose_name='Rođeno prezime')),
                            ('sex', models.CharField(choices=[('female', 'Ženski'), ('male', 'Muški'), ('unknown', 'Nepoznato / nepotvrđeno')], default='unknown', max_length=12, verbose_name='Spol')),
                            ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Datum rođenja')),
                            ('place_of_birth', models.CharField(blank=True, max_length=180, verbose_name='Mjesto rođenja')),
                            ('normalized_given_names', models.CharField(db_index=True, editable=False, max_length=160)),
                            ('normalized_surname', models.CharField(db_index=True, editable=False, max_length=160)),
                            ('status', models.CharField(choices=[('active', 'Aktivna'), ('merged', 'Spojena'), ('archived', 'Arhivirana')], db_index=True, default='active', max_length=12, verbose_name='Status')),
                            ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                            ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                            ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_as_father', to='zupa_vjernici.person', verbose_name='Otac')),
                            ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_as_mother', to='zupa_vjernici.person', verbose_name='Majka')),
                            ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persons', to='pastoral.parish', verbose_name='Župa')),
                        ],
                        options={
                            'verbose_name': 'Osoba',
                            'verbose_name_plural': 'Osobe',
                            'db_table': 'pastoral_person',
                            'ordering': ('surname', 'given_names', 'date_of_birth'),
                        },
                    ),
                    migrations.CreateModel(
                        name='ChurchEnrollment',
                        fields=[
                            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                            ('valid_from', models.DateField(blank=True, null=True, verbose_name='Vrijedi od')),
                            ('valid_until', models.DateField(blank=True, null=True, verbose_name='Vrijedi do')),
                            ('enrollment_basis', models.CharField(blank=True, max_length=200, verbose_name='Temelj pripadnosti')),
                            ('decree_reference', models.CharField(blank=True, max_length=200, verbose_name='Referenca dekreta')),
                            ('status', models.CharField(choices=[('unconfirmed', 'Nepotvrđeno'), ('confirmed', 'Potvrđeno')], db_index=True, default='unconfirmed', max_length=12, verbose_name='Status')),
                            ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                            ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                            ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='church_enrollments', to='pastoral.parish', verbose_name='Župa')),
                            ('previous_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='following_enrollments', to='zupa_vjernici.churchenrollment', verbose_name='Prethodna pripadnost')),
                            ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_church_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Evidentirao')),
                            ('church_sui_iuris', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_enrollments', to='zupa_vjernici.churchsuiiuris', verbose_name='Crkva sui iuris')),
                            ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='church_enrollments', to='zupa_vjernici.person', verbose_name='Osoba')),
                        ],
                        options={
                            'verbose_name': 'Pripadnost Crkvi sui iuris',
                            'verbose_name_plural': 'Pripadnosti Crkvi sui iuris',
                            'db_table': 'pastoral_churchenrollment',
                            'ordering': ('person', '-valid_from', '-created_at'),
                        },
                    ),
                    migrations.AddIndex(
                        model_name='person',
                        index=models.Index(fields=['parish', 'normalized_surname', 'normalized_given_names'], name='person_parish_name_lookup'),
                    ),
                    migrations.AddIndex(
                        model_name='person',
                        index=models.Index(fields=['parish', 'date_of_birth'], name='person_parish_birth_lookup'),
                    ),
                    migrations.AddIndex(
                        model_name='churchenrollment',
                        index=models.Index(fields=['parish', 'status'], name='enrollment_parish_status'),
                    ),
                    migrations.AddConstraint(
                        model_name='churchenrollment',
                        constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_from__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='enrollment_valid_period'),
                    ),
                    migrations.AddConstraint(
                        model_name='churchenrollment',
                        constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed'), ('valid_until__isnull', True)), fields=('person',), name='one_current_confirmed_enrollment'),
                    ),
            ],
            database_operations=[],
        ),
    ]
