# Generated by Django 5.2.16 on 2026-08-21 11:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0031_operational_parish_store'),
        ('zupa_vjernici', '0001_move_domain_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('zone', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='pastoral.parish')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('surname', models.CharField(blank=True, max_length=160)),
                ('street_public_identifier', models.CharField(blank=True, max_length=64)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(blank=True, default='aktivna', max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to='pastoral.parish')),
                ('street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='households', to='zupa_vjernici.street')),
            ],
            options={
                'ordering': ['surname', 'public_identifier'],
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
        migrations.CreateModel(
            name='PastoralVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('family_public_identifier', models.CharField(blank=True, max_length=64)),
                ('scheduled_on', models.DateField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='zupa_vjernici.household')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastoral_visits', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
    ]
