# Generated by Django 5.2.16 on 2026-09-18 09:00

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


def _backfill_household_memberships(apps, schema_editor):
    HouseholdMember = apps.get_model('zupa_vjernici', 'HouseholdMember')
    HouseholdMembership = apps.get_model('zupa_vjernici', 'HouseholdMembership')
    for member in HouseholdMember.objects.all().iterator():
        HouseholdMembership.objects.update_or_create(
            household_id=member.household_id,
            public_identifier=member.public_identifier,
            defaults={
                'historical_name': member.name,
                'role': member.relation,
                'notes': member.notes,
                'sort_order': member.sort_order,
                'unified_key': f'{member.household_id}::{member.public_identifier}',
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('zupa_vjernici', '0004_typed_household_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchenrollment',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='churchenrollment',
            name='date_from',
            field=models.DateField(default=datetime.date.today, verbose_name='Vrijedi od'),
        ),
        migrations.AddField(
            model_name='churchenrollment',
            name='date_to',
            field=models.DateField(db_index=True, default=datetime.date(9999, 12, 31), verbose_name='Vrijedi do'),
        ),
        migrations.AddField(
            model_name='churchenrollment',
            name='unified_key',
            field=models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ'),
        ),
        migrations.AddField(
            model_name='churchsuiiuris',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='churchsuiiuris',
            name='unified_key',
            field=models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ'),
        ),
        migrations.AddField(
            model_name='ecclesiasticaljurisdiction',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='ecclesiasticaljurisdiction',
            name='unified_key',
            field=models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ'),
        ),
        migrations.AddField(
            model_name='household',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='household',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='household',
            name='date_from',
            field=models.DateField(default=datetime.date.today, verbose_name='Vrijedi od'),
        ),
        migrations.AddField(
            model_name='household',
            name='date_to',
            field=models.DateField(db_index=True, default=datetime.date(9999, 12, 31), verbose_name='Vrijedi do'),
        ),
        migrations.AddField(
            model_name='household',
            name='house_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='household',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno'),
        ),
        migrations.AddField(
            model_name='household',
            name='unified_key',
            field=models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ'),
        ),
        migrations.AddField(
            model_name='householdcontribution',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='householdcontribution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='householdcontribution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AddField(
            model_name='householdrelative',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='householdrelative',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='householdrelative',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AddField(
            model_name='pastoralvisit',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='pastoralvisit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='person',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno'),
        ),
        migrations.AddField(
            model_name='person',
            name='unified_key',
            field=models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ'),
        ),
        migrations.AddField(
            model_name='street',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='street',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='street',
            name='date_from',
            field=models.DateField(default=datetime.date.today, verbose_name='Vrijedi od'),
        ),
        migrations.AddField(
            model_name='street',
            name='date_to',
            field=models.DateField(db_index=True, default=datetime.date(9999, 12, 31), verbose_name='Vrijedi do'),
        ),
        migrations.AddField(
            model_name='street',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno'),
        ),
        migrations.AddField(
            model_name='street',
            name='unified_key',
            field=models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ'),
        ),
        migrations.AlterField(
            model_name='churchenrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='churchsuiiuris',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='churchsuiiuris',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno'),
        ),
        migrations.AlterField(
            model_name='ecclesiasticaljurisdiction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='ecclesiasticaljurisdiction',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno'),
        ),
        migrations.AlterField(
            model_name='household',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AlterField(
            model_name='pastoralvisit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='street',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.CreateModel(
            name='HouseholdMembership',
            fields=[
                ('content_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('date_from', models.DateField(default=datetime.date.today, verbose_name='Vrijedi od')),
                ('date_to', models.DateField(db_index=True, default=datetime.date(9999, 12, 31), verbose_name='Vrijedi do')),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('historical_name', models.CharField(blank=True, max_length=160)),
                ('role', models.CharField(blank=True, max_length=80)),
                ('is_head', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='zupa_vjernici.household')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='household_memberships', to='zupa_vjernici.person')),
            ],
            options={
                'verbose_name': 'Članstvo u kućanstvu',
                'verbose_name_plural': 'Članstva u kućanstvu',
                'ordering': ['sort_order', 'historical_name'],
                'unique_together': {('household', 'public_identifier')},
            },
        ),
        migrations.RunPython(_backfill_household_memberships, migrations.RunPython.noop),
    ]
