# Generated by Django 5.2.16 on 2026-09-18 09:38

import unicodedata
import uuid
from datetime import date

from django.db import migrations, models


def _normalize(value: str) -> str:
    decomposed_value = unicodedata.normalize('NFKD', value or '')
    characters_without_accents = (
        character
        for character in decomposed_value
        if not unicodedata.combining(character)
    )
    return ' '.join(''.join(characters_without_accents).casefold().split())


def _split_name(full_name: str, fallback_surname: str) -> tuple[str, str]:
    parts = [part for part in str(full_name or '').split() if part]
    if not parts:
        return '', fallback_surname
    if len(parts) == 1:
        return parts[0], fallback_surname or parts[0]
    return ' '.join(parts[:-1]), parts[-1]


def _sex_from_relation(relation: str) -> str:
    normalized = str(relation or '').casefold()
    if normalized in {'majka', 'žena', 'zena', 'kći', 'kci', 'wife'}:
        return 'female'
    if normalized in {'otac', 'muž', 'muz', 'sin', 'husband'}:
        return 'male'
    return 'unknown'


def _find_or_create_person(Person, parish_id, full_name, fallback_surname, relation, birth_year, place_of_birth=''):
    given_names, surname = _split_name(full_name, fallback_surname)
    if not given_names and not surname:
        return None
    if not given_names:
        given_names = surname
    if not surname:
        surname = fallback_surname or given_names
    normalized_given = _normalize(given_names)
    normalized_surname = _normalize(surname)
    queryset = Person.objects.filter(
        parish_id=parish_id,
        normalized_given_names=normalized_given,
        normalized_surname=normalized_surname,
    )
    person = queryset.first()
    year_text = str(birth_year or '').strip()
    date_of_birth = None
    if year_text.isdigit():
        year_value = int(year_text)
        if 1800 <= year_value <= 2200:
            date_of_birth = date(year_value, 1, 1)
    if person is None:
        person = Person(
            id=uuid.uuid4(),
            parish_id=parish_id,
            given_names=given_names[:160],
            surname=surname[:160],
            sex=_sex_from_relation(relation),
            date_of_birth=date_of_birth,
            place_of_birth=str(place_of_birth or '')[:180],
            normalized_given_names=normalized_given[:160],
            normalized_surname=normalized_surname[:160],
            status='active',
            unified_key=f'{parish_id}::{normalized_surname}::{normalized_given}',
        )
        person.save()
    return person


def _backfill_persons_and_memberships(apps, schema_editor):
    Household = apps.get_model('zupa_vjernici', 'Household')
    HouseholdMember = apps.get_model('zupa_vjernici', 'HouseholdMember')
    HouseholdRelative = apps.get_model('zupa_vjernici', 'HouseholdRelative')
    HouseholdMembership = apps.get_model('zupa_vjernici', 'HouseholdMembership')
    Person = apps.get_model('zupa_vjernici', 'Person')
    SacramentalEvent = apps.get_model('sakramenti', 'SacramentalEvent')
    EventParticipant = apps.get_model('sakramenti', 'EventParticipant')

    label_to_type = {
        'krštenje': 'baptism',
        'krstenje': 'baptism',
        'pričest': 'first_communion',
        'pricest': 'first_communion',
        'krizma': 'confirmation',
        'vjenčanje': 'marriage',
        'vjencanje': 'marriage',
        'pomazanje': 'anointing',
    }

    for member in HouseholdMember.objects.select_related('household').iterator():
        household = member.household
        person = _find_or_create_person(
            Person,
            household.parish_id,
            member.name,
            household.surname,
            member.relation,
            member.birth_year,
        )
        HouseholdMembership.objects.update_or_create(
            household=household,
            public_identifier=member.public_identifier,
            defaults={
                'person': person,
                'historical_name': member.name,
                'role': member.relation,
                'lives_in_household': True,
                'recorded_birth_year': member.birth_year or '',
                'pastoral_roles': list(member.roles or []),
                'notes': member.notes,
                'sort_order': member.sort_order,
                'unified_key': f'{household.id}::{member.public_identifier}',
            },
        )
        if person is None:
            continue
        for label in member.sacraments or []:
            event_type = label_to_type.get(str(label).strip().casefold())
            if not event_type:
                continue
            public_identifier = f'family-card:{person.id}:{event_type}'
            event, _created = SacramentalEvent.objects.get_or_create(
                parish_id=household.parish_id,
                event_type=event_type,
                public_identifier=public_identifier,
                defaults={
                    'id': uuid.uuid4(),
                    'status': 'legacy_imported',
                    'source': 'legacy_import',
                },
            )
            EventParticipant.objects.get_or_create(
                event=event,
                person=person,
                role='recipient',
                defaults={
                    'id': uuid.uuid4(),
                    'parish_id': household.parish_id,
                    'historical_name': member.name or str(person),
                },
            )

    for relative in HouseholdRelative.objects.select_related('household').iterator():
        household = relative.household
        person = _find_or_create_person(
            Person,
            household.parish_id,
            relative.name,
            household.surname,
            relative.relation,
            relative.birth_year,
        )
        HouseholdMembership.objects.update_or_create(
            household=household,
            public_identifier=relative.public_identifier,
            defaults={
                'person': person,
                'historical_name': relative.name,
                'role': relative.relation,
                'lives_in_household': False,
                'recorded_birth_year': relative.birth_year or '',
                'notes': relative.notes,
                'sort_order': 1000 + relative.sort_order,
                'unified_key': f'{household.id}::{relative.public_identifier}',
            },
        )

    for household in Household.objects.all().iterator():
        for side, payload in (('husband', household.husband), ('wife', household.wife)):
            if not isinstance(payload, dict):
                continue
            full_name = str(payload.get('name') or '').strip()
            if not full_name:
                continue
            relation = 'muž' if side == 'husband' else 'žena'
            person = _find_or_create_person(
                Person,
                household.parish_id,
                full_name,
                household.surname,
                relation,
                payload.get('birthYear'),
                payload.get('birthPlace') or '',
            )
            matching = None
            if person is not None:
                matching = HouseholdMembership.objects.filter(
                    household=household,
                    person=person,
                    lives_in_household=True,
                ).first()
            public_identifier = (
                matching.public_identifier if matching else f'spouse-{side}'
            )
            HouseholdMembership.objects.update_or_create(
                household=household,
                public_identifier=public_identifier,
                defaults={
                    'person': person,
                    'historical_name': full_name,
                    'role': matching.role if matching else relation,
                    'spouse_side': side,
                    'lives_in_household': True,
                    'is_head': side == 'husband',
                    'recorded_birth_year': str(payload.get('birthYear') or ''),
                    'notes': str(payload.get('notes') or ''),
                    'unified_key': f'{household.id}::{public_identifier}',
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('sakramenti', '0002_scd_fact_bases'),
        ('zupa_vjernici', '0005_scd_fact_bases'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdmembership',
            name='lives_in_household',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='householdmembership',
            name='pastoral_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='householdmembership',
            name='recorded_birth_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='householdmembership',
            name='spouse_side',
            field=models.CharField(blank=True, choices=[('', 'Nije bračni karton'), ('husband', 'Muž'), ('wife', 'Žena')], default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='householdmembership',
            name='role',
            field=models.CharField(blank=True, help_text='Slobodni tekst iz kartona (majka, sin, rođak…).', max_length=80, verbose_name='Odnos u obitelji'),
        ),
        migrations.RunPython(_backfill_persons_and_memberships, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='householdrelative',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='householdrelative',
            name='household',
        ),
        migrations.RemoveField(
            model_name='household',
            name='husband',
        ),
        migrations.RemoveField(
            model_name='household',
            name='wife',
        ),
        migrations.DeleteModel(
            name='HouseholdMember',
        ),
        migrations.DeleteModel(
            name='HouseholdRelative',
        ),
    ]
