# Generated by Django 5.2.16 on 2026-08-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parishwebsite',
            name='about_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parishwebsite',
            name='address',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='parishwebsite',
            name='confession_schedule',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parishwebsite',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='parishwebsite',
            name='donation_purpose',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='parishwebsite',
            name='donation_recipient',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='parishwebsite',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='parishwebsite',
            name='iban',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='parishwebsite',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='parishwebsite',
            name='map_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='parishwebsite',
            name='office_hours',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parishwebsite',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='parishwebsite',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
