# Generated by Django 5.2.16 on 2026-08-21 11:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pastoral', '0031_operational_parish_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
        migrations.CreateModel(
            name='CouncilBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pastoralCouncil', 'Pastoralno vijeće'), ('economicCouncil', 'Ekonomsko vijeće'), ('parishDecree', 'Osnivački dekret')], max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='council_bundles', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='DocumentBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_bindings', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
        migrations.CreateModel(
            name='OfficeDirectoryRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('appGroups', 'Grupa'), ('appUsers', 'Korisnik'), ('parishPriests', 'Svećenik')], max_length=40)),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_directory_records', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'kind', 'public_identifier')},
            },
        ),
        migrations.CreateModel(
            name='OfficeTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_tasks', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
        migrations.CreateModel(
            name='ParishCalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
        migrations.CreateModel(
            name='PublicSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_submissions', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
        migrations.CreateModel(
            name='StaffMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_messages', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
    ]
