# Generated by Django 5.2.16 on 2026-09-21 08:23

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pastoral', '0002_initial'),
        ('sakramenti', '0001_initial'),
        ('zupa_vjernici', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('is_active', models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('council_type', models.CharField(choices=[('pastoral', 'Pastoralno vijeće'), ('economic', 'Ekonomsko vijeće')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=220)),
                ('established_on', models.DateField(blank=True, null=True)),
                ('last_meeting_on', models.DateField(blank=True, null=True)),
                ('next_meeting_on', models.DateField(blank=True, null=True)),
                ('budget_year', models.PositiveIntegerField(blank=True, null=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='councils', to='pastoral.parish')),
            ],
            options={
                'verbose_name': 'Vijeće',
                'verbose_name_plural': 'Vijeća',
                'unique_together': {('parish', 'council_type')},
            },
        ),
        migrations.CreateModel(
            name='ParishFoundingDecree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('is_active', models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('official_name', models.CharField(blank=True, max_length=220)),
                ('established_text', models.CharField(blank=True, max_length=80)),
                ('territory', models.CharField(blank=True, max_length=255)),
                ('decree_reference', models.CharField(blank=True, max_length=255)),
                ('parish', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='founding_decree', to='pastoral.parish')),
            ],
            options={
                'verbose_name': 'Osnivački dekret župe',
                'verbose_name_plural': 'Osnivački dekreti župa',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('announced_at', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
        migrations.CreateModel(
            name='CouncilMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('date_from', models.DateField(default=datetime.date.today, verbose_name='Vrijedi od')),
                ('date_to', models.DateField(db_index=True, default=datetime.date(9999, 12, 31), verbose_name='Vrijedi do')),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('member_name', models.CharField(blank=True, max_length=220)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ured.council')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='council_memberships', to='zupa_vjernici.person')),
            ],
            options={
                'verbose_name': 'Članstvo u vijeću',
                'verbose_name_plural': 'Članstva u vijeću',
                'constraints': [models.UniqueConstraint(condition=models.Q(('date_to', datetime.date(9999, 12, 31))), fields=('council', 'public_identifier'), name='councilmembership_one_current_id')],
            },
        ),
        migrations.CreateModel(
            name='DocumentBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_bindings', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
        migrations.CreateModel(
            name='OfficeTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, default='srednja', max_length=40)),
                ('is_done', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_tasks', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
        migrations.CreateModel(
            name='ParishCalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=160)),
                ('event_type', models.CharField(blank=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
        migrations.CreateModel(
            name='PublicSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('form_type', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('person_name', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.CharField(blank=True, max_length=160)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.CharField(blank=True, max_length=64)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('converted_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_public_submissions', to='sakramenti.formationcandidate')),
                ('converted_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_public_submissions', to='sakramenti.sacramentalevent')),
                ('converted_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_public_submissions', to='zupa_vjernici.person')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_submissions', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
    ]
