# Generated by Django 5.2.16 on 2026-09-18 09:00

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0036_scd_fact_bases'),
        ('sakramenti', '0002_scd_fact_bases'),
        ('ured', '0002_typed_office_fields'),
        ('zupa_vjernici', '0005_scd_fact_bases'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='councilbundle',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='councilbundle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='documentbinding',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='documentbinding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='officedirectoryrecord',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='officedirectoryrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='officetask',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='officetask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='parishcalendarevent',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='parishcalendarevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='publicsubmission',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='publicsubmission',
            name='converted_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_public_submissions', to='sakramenti.formationcandidate'),
        ),
        migrations.AddField(
            model_name='publicsubmission',
            name='converted_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_public_submissions', to='sakramenti.sacramentalevent'),
        ),
        migrations.AddField(
            model_name='publicsubmission',
            name='converted_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_public_submissions', to='zupa_vjernici.person'),
        ),
        migrations.AddField(
            model_name='publicsubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='staffmessage',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='staffmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AlterField(
            model_name='councilbundle',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='councilbundle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AlterField(
            model_name='documentbinding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AlterField(
            model_name='officedirectoryrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AlterField(
            model_name='officetask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AlterField(
            model_name='parishcalendarevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AlterField(
            model_name='publicsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AlterField(
            model_name='staffmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.CreateModel(
            name='Council',
            fields=[
                ('content_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('is_active', models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('council_type', models.CharField(choices=[('pastoral', 'Pastoralno vijeće'), ('economic', 'Ekonomsko vijeće')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=220)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='councils', to='pastoral.parish')),
            ],
            options={
                'verbose_name': 'Vijeće',
                'verbose_name_plural': 'Vijeća',
                'unique_together': {('parish', 'council_type')},
            },
        ),
        migrations.CreateModel(
            name='CouncilMembership',
            fields=[
                ('content_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('date_from', models.DateField(default=datetime.date.today, verbose_name='Vrijedi od')),
                ('date_to', models.DateField(db_index=True, default=datetime.date(9999, 12, 31), verbose_name='Vrijedi do')),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('member_name', models.CharField(blank=True, max_length=220)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ured.council')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='council_memberships', to='zupa_vjernici.person')),
            ],
            options={
                'verbose_name': 'Članstvo u vijeću',
                'verbose_name_plural': 'Članstva u vijeću',
                'unique_together': {('council', 'public_identifier')},
            },
        ),
    ]
