# Generated by Django 5.2.16 on 2026-09-18 09:38

import uuid
from datetime import date

import django.db.models.deletion
from django.db import migrations, models


def _parse_iso_date(value):
    raw = str(value or '').strip()
    if not raw or raw in {'—', '-'}:
        return None
    try:
        return date.fromisoformat(raw[:10])
    except ValueError:
        return None


def _backfill_councils(apps, schema_editor):
    Council = apps.get_model('ured', 'Council')
    CouncilMembership = apps.get_model('ured', 'CouncilMembership')
    CouncilBundle = apps.get_model('ured', 'CouncilBundle')
    ParishFoundingDecree = apps.get_model('ured', 'ParishFoundingDecree')

    kind_to_type = {
        'pastoralCouncil': 'pastoral',
        'economicCouncil': 'economic',
    }
    for bundle in CouncilBundle.objects.all().iterator():
        payload = bundle.payload or {}
        if bundle.kind == 'parishDecree':
            ParishFoundingDecree.objects.update_or_create(
                parish_id=bundle.parish_id,
                defaults={
                    'id': uuid.uuid4(),
                    'official_name': str(payload.get('name') or ''),
                    'established_text': str(payload.get('established') or '')[:80],
                    'territory': str(payload.get('territory') or ''),
                    'decree_reference': str(payload.get('decreeRef') or ''),
                    'unified_key': str(bundle.parish_id),
                },
            )
            continue
        council_type = kind_to_type.get(bundle.kind)
        if not council_type:
            continue
        title = (
            'Župno ekonomsko vijeće'
            if council_type == 'economic'
            else 'Župno pastoralno vijeće'
        )
        budget_year = payload.get('budgetYear')
        try:
            budget_year_value = int(budget_year) if budget_year not in (None, '') else None
        except (TypeError, ValueError):
            budget_year_value = None
        council, _created = Council.objects.update_or_create(
            parish_id=bundle.parish_id,
            council_type=council_type,
            defaults={
                'title': title,
                'established_on': _parse_iso_date(payload.get('established')),
                'last_meeting_on': _parse_iso_date(
                    payload.get('lastMeeting') or payload.get('lastReview')
                ),
                'next_meeting_on': _parse_iso_date(
                    payload.get('nextMeeting') or payload.get('nextReview')
                ),
                'budget_year': budget_year_value,
                'unified_key': f'{bundle.parish_id}::{council_type}',
            },
        )
        members = payload.get('members') if isinstance(payload.get('members'), list) else []
        for index, member_record in enumerate(members):
            if not isinstance(member_record, dict):
                continue
            public_identifier = str(member_record.get('id') or f'{council_type}-{index + 1}')
            CouncilMembership.objects.update_or_create(
                council=council,
                public_identifier=public_identifier,
                defaults={
                    'member_name': str(member_record.get('name') or ''),
                    'role': str(member_record.get('role') or ''),
                    'phone': str(member_record.get('phone') or ''),
                    'is_confirmed': bool(member_record.get('confirmed')),
                    'unified_key': f'{council.id}::{public_identifier}',
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0037_person_councils_drop_phase_two'),
        ('ured', '0003_scd_fact_bases'),
    ]

    operations = [
        migrations.AddField(
            model_name='council',
            name='budget_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='council',
            name='established_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='council',
            name='last_meeting_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='council',
            name='next_meeting_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='councilmembership',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='councilmembership',
            name='phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='ParishFoundingDecree',
            fields=[
                ('content_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('is_active', models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('official_name', models.CharField(blank=True, max_length=220)),
                ('established_text', models.CharField(blank=True, max_length=80)),
                ('territory', models.CharField(max_length=255, blank=True)),
                ('decree_reference', models.CharField(blank=True, max_length=255)),
                ('parish', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='founding_decree', to='pastoral.parish')),
            ],
            options={
                'verbose_name': 'Osnivački dekret župe',
                'verbose_name_plural': 'Osnivački dekreti župa',
            },
        ),
        migrations.RunPython(_backfill_councils, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='officedirectoryrecord',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='officedirectoryrecord',
            name='parish',
        ),
        migrations.AlterUniqueTogether(
            name='staffmessage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='staffmessage',
            name='parish',
        ),
        migrations.DeleteModel(
            name='CouncilBundle',
        ),
        migrations.DeleteModel(
            name='OfficeDirectoryRecord',
        ),
        migrations.DeleteModel(
            name='StaffMessage',
        ),
    ]
