# Generated by Django 5.2.16 on 2026-09-21 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiturgicalCalendarEntry',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('provider', models.CharField(choices=[('romcal-croatia', 'Romcal — kalendar za Hrvatsku'), ('manual', 'Ručni unos')], db_index=True, default='romcal-croatia', max_length=30, verbose_name='Izvor')),
                ('date', models.DateField(db_index=True, verbose_name='Datum')),
                ('name', models.CharField(max_length=255, verbose_name='Svetac ili slavlje')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Izvorni naziv')),
                ('liturgical_color', models.CharField(choices=[('white', 'Bijela'), ('red', 'Crvena'), ('green', 'Zelena'), ('purple', 'Ljubičasta'), ('rose', 'Ružičasta'), ('black', 'Crna'), ('other', 'Druga / nepoznata')], db_index=True, default='other', max_length=20, verbose_name='Liturgijska boja')),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Stupanj slavlja; veći broj znači viši prioritet.', verbose_name='Prioritet')),
                ('priority_label', models.CharField(blank=True, max_length=120, verbose_name='Naziv prioriteta (svetkovina, blagdan, svagdan)')),
                ('is_primary', models.BooleanField(db_index=True, default=True, verbose_name='Glavno slavlje dana')),
            ],
            options={
                'verbose_name': 'Liturgijski kalendarski zapis',
                'verbose_name_plural': 'Liturgijski kalendarski zapisi',
                'db_table': 'pastoral_liturgicalcalendarentry',
                'ordering': ['date', '-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LiturgicalTradition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('is_active', models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Naziv')),
                ('description', models.CharField(max_length=160, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Liturgijska tradicija',
                'verbose_name_plural': 'Liturgijske tradicije',
                'db_table': 'pastoral_liturgicaltradition',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MassException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('exception_date', models.DateField(blank=True, db_index=True, null=True)),
                ('cancel_all', models.BooleanField(default=False)),
                ('cancel_times', models.JSONField(blank=True, default=list)),
                ('add_slots', models.JSONField(blank=True, default=list)),
                ('note', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MassIntention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('intention_date', models.DateField(db_index=True)),
                ('mass_time', models.CharField(max_length=20)),
                ('intention_for', models.CharField(max_length=255)),
                ('stipend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MassScheduleSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('is_active', models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('day_label', models.CharField(blank=True, max_length=80)),
                ('mass_time', models.CharField(blank=True, max_length=20)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('no_mass', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BulletinIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('week_start', models.DateField(db_index=True, help_text='Početak razdoblja na koje se listić odnosi (obično ponedjeljak).', verbose_name='Od')),
                ('week_end', models.DateField(help_text='Kraj razdoblja (obično nedjelja istog tjedna).', verbose_name='Do')),
                ('title', models.CharField(max_length=255, verbose_name='Naslov')),
                ('status', models.CharField(choices=[('nacrt', 'Nacrt'), ('izdan', 'Izdan')], db_index=True, default='izdan', max_length=16, verbose_name='Status')),
                ('layout', models.JSONField(blank=True, default=dict, help_text='Snapshot blokova ovog broja (`blocks`), ne predložak župe.', verbose_name='Blokovi izdanja')),
                ('rendered_html', models.TextField(blank=True, help_text='Arhiva ispisa; reprint ne ovisi o kasnijim nakanama i rasporedu.', verbose_name='HTML ispisa')),
            ],
            options={
                'verbose_name': 'Župni listić',
                'verbose_name_plural': 'Župni listići',
                'ordering': ('-week_start', '-created_at'),
                'constraints': [models.CheckConstraint(condition=models.Q(('week_end__gte', models.F('week_start'))), name='listic_week_end_gte_start')],
            },
        ),
    ]
