# Generated by Django 5.2.16 on 2026-08-21 11:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.migrations.operations.special import SeparateDatabaseAndState


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pastoral', '0028_harden_otp_challenges'),
    ]

    operations = [
        SeparateDatabaseAndState(
            state_operations=[

                    migrations.CreateModel(
                        name='LiturgicalTradition',
                        fields=[
                            ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                            ('code', models.SlugField(unique=True, verbose_name='Stabilni kod')),
                            ('name', models.CharField(max_length=160, verbose_name='Naziv')),
                            ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktivno')),
                            ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                            ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                        ],
                        options={
                            'verbose_name': 'Liturgijska tradicija',
                            'verbose_name_plural': 'Liturgijske tradicije',
                            'db_table': 'pastoral_liturgicaltradition',
                            'ordering': ('name',),
                        },
                    ),
                    migrations.CreateModel(
                        name='LiturgicalCalendarImport',
                        fields=[
                            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                            ('year', models.PositiveSmallIntegerField(verbose_name='Godina')),
                            ('provider', models.CharField(choices=[('litcal-va', 'LitCal — opći rimski kalendar')], default='litcal-va', max_length=30, verbose_name='Izvor')),
                            ('events', models.JSONField(default=list, editable=False, verbose_name='Uvezeni događaji')),
                            ('event_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Broj događaja')),
                            ('source_file_name', models.CharField(blank=True, editable=False, max_length=255, verbose_name='Izvorna datoteka')),
                            ('checksum', models.CharField(blank=True, editable=False, max_length=64, verbose_name='SHA-256 kontrolni zbroj')),
                            ('imported_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Vrijeme uvoza')),
                            ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                            ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                            ('imported_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liturgical_calendar_imports', to=settings.AUTH_USER_MODEL, verbose_name='Uvezao')),
                        ],
                        options={
                            'verbose_name': 'Uvoz liturgijskog kalendara',
                            'verbose_name_plural': 'Uvozi liturgijskog kalendara',
                            'db_table': 'pastoral_liturgicalcalendarimport',
                            'ordering': ['-year', 'provider'],
                        },
                    ),
                    migrations.CreateModel(
                        name='LiturgicalCalendarEntry',
                        fields=[
                            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                            ('date', models.DateField(db_index=True, verbose_name='Datum')),
                            ('name', models.CharField(max_length=255, verbose_name='Svetac ili slavlje')),
                            ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Izvorni naziv')),
                            ('liturgical_color', models.CharField(choices=[('white', 'Bijela'), ('red', 'Crvena'), ('green', 'Zelena'), ('purple', 'Ljubičasta'), ('rose', 'Ružičasta'), ('black', 'Crna'), ('other', 'Druga / nepoznata')], db_index=True, default='other', max_length=20, verbose_name='Liturgijska boja')),
                            ('priority', models.PositiveSmallIntegerField(default=0, help_text='LitCal stupanj slavlja; veći broj znači viši prioritet.', verbose_name='Prioritet')),
                            ('priority_label', models.CharField(blank=True, max_length=120, verbose_name='Naziv prioriteta')),
                            ('is_primary', models.BooleanField(db_index=True, default=False, verbose_name='Glavno slavlje dana')),
                            ('external_identifier', models.CharField(blank=True, max_length=160, verbose_name='Identifikator izvora')),
                            ('source_position', models.PositiveIntegerField(verbose_name='Redni broj u importu')),
                            ('raw_data', models.JSONField(default=dict, editable=False, verbose_name='Izvorni podaci')),
                            ('calendar_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='liturgija.liturgicalcalendarimport', verbose_name='Kalendarski import')),
                        ],
                        options={
                            'verbose_name': 'Liturgijski kalendarski zapis',
                            'verbose_name_plural': 'Liturgijski kalendarski zapisi',
                            'db_table': 'pastoral_liturgicalcalendarentry',
                            'ordering': ['date', '-is_primary', '-priority', 'name'],
                        },
                    ),
                    migrations.AddConstraint(
                        model_name='liturgicalcalendarimport',
                        constraint=models.UniqueConstraint(fields=('year', 'provider'), name='unique_liturgical_calendar_import'),
                    ),
                    migrations.AddIndex(
                        model_name='liturgicalcalendarentry',
                        index=models.Index(fields=['date', 'is_primary'], name='liturgical_date_primary_idx'),
                    ),
                    migrations.AddConstraint(
                        model_name='liturgicalcalendarentry',
                        constraint=models.UniqueConstraint(fields=('calendar_import', 'source_position'), name='unique_liturgical_entry_source_position'),
                    ),
            ],
            database_operations=[],
        ),
    ]
