# Generated by Django 5.2.16 on 2026-08-21 11:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liturgija', '0001_move_domain_models'),
        ('pastoral', '0031_operational_parish_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinLayout',
            fields=[
                ('parish', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bulletin_layout', serialize=False, to='pastoral.parish')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('template_payload', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BulletinIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_issues', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
        migrations.CreateModel(
            name='MassException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_exceptions', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
        migrations.CreateModel(
            name='MassIntention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_intentions', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
        migrations.CreateModel(
            name='MassScheduleLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_schedule_log_entries', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
        migrations.CreateModel(
            name='MassScheduleSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_schedule_slots', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
    ]
