# Generated by Django 5.2.16 on 2026-09-21 08:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('liturgija', '0001_initial'),
        ('pastoral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinLayout',
            fields=[
                ('parish', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bulletin_layout', serialize=False, to='pastoral.parish')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('template_payload', models.JSONField(blank=True, null=True)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiturgicalTradition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('is_active', models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('code', models.SlugField(unique=True, verbose_name='Stabilni kod')),
                ('name', models.CharField(max_length=160, verbose_name='Naziv')),
            ],
            options={
                'verbose_name': 'Liturgijska tradicija',
                'verbose_name_plural': 'Liturgijske tradicije',
                'db_table': 'pastoral_liturgicaltradition',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='bulletinissue',
            name='parish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_issues', to='pastoral.parish'),
        ),
        migrations.CreateModel(
            name='LiturgicalCalendarEntry',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('provider', models.CharField(choices=[('litcal-va', 'LitCal — opći rimski kalendar'), ('romcal-croatia', 'Romcal — kalendar za Hrvatsku'), ('manual', 'Ručni unos')], db_index=True, default='litcal-va', max_length=30, verbose_name='Izvor')),
                ('date', models.DateField(db_index=True, verbose_name='Datum')),
                ('name', models.CharField(max_length=255, verbose_name='Svetac ili slavlje')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Izvorni naziv')),
                ('liturgical_color', models.CharField(choices=[('white', 'Bijela'), ('red', 'Crvena'), ('green', 'Zelena'), ('purple', 'Ljubičasta'), ('rose', 'Ružičasta'), ('black', 'Crna'), ('other', 'Druga / nepoznata')], db_index=True, default='other', max_length=20, verbose_name='Liturgijska boja')),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Stupanj slavlja; veći broj znači viši prioritet.', verbose_name='Prioritet')),
                ('priority_label', models.CharField(blank=True, max_length=120, verbose_name='Naziv prioriteta')),
                ('is_primary', models.BooleanField(db_index=True, default=True, verbose_name='Glavno slavlje dana')),
                ('external_identifier', models.CharField(blank=True, max_length=160, verbose_name='Identifikator izvora')),
                ('raw_data', models.JSONField(default=dict, editable=False, verbose_name='Izvorni podaci')),
            ],
            options={
                'verbose_name': 'Liturgijski kalendarski zapis',
                'verbose_name_plural': 'Liturgijski kalendarski zapisi',
                'db_table': 'pastoral_liturgicalcalendarentry',
                'ordering': ['date', '-priority', 'name'],
                'indexes': [models.Index(fields=['date', 'is_primary'], name='liturgical_date_primary_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'date', 'external_identifier'), name='unique_liturgical_entry_source_celebration')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='bulletinissue',
            unique_together={('parish', 'public_identifier')},
        ),
        migrations.CreateModel(
            name='MassException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('exception_date', models.DateField(blank=True, db_index=True, null=True)),
                ('cancel_all', models.BooleanField(default=False)),
                ('cancel_times', models.JSONField(blank=True, default=list)),
                ('add_slots', models.JSONField(blank=True, default=list)),
                ('note', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_exceptions', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
        migrations.CreateModel(
            name='MassIntention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('intention_date', models.DateField(blank=True, db_index=True, null=True)),
                ('mass_time', models.CharField(blank=True, max_length=20)),
                ('requested_by', models.CharField(blank=True, max_length=160)),
                ('intention_for', models.CharField(blank=True, max_length=255)),
                ('stipend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('requested', 'Zatraženo'), ('scheduled', 'Raspoređeno'), ('fulfilled', 'Ispunjeno'), ('transferred', 'Upućeno'), ('cancelled', 'Otkazano')], db_index=True, default='requested', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_intentions', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
        migrations.CreateModel(
            name='MassScheduleLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('logged_at', models.CharField(blank=True, max_length=64)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_schedule_log_entries', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
        migrations.CreateModel(
            name='MassScheduleSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('is_active', models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('public_identifier', models.CharField(db_index=True, max_length=64)),
                ('day_label', models.CharField(blank=True, max_length=80)),
                ('mass_time', models.CharField(blank=True, max_length=20)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('celebrant', models.CharField(blank=True, max_length=160)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('no_mass', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_schedule_slots', to='pastoral.parish')),
            ],
            options={
                'unique_together': {('parish', 'public_identifier')},
            },
        ),
    ]
