# Generated by Django 5.2.16 on 2026-09-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liturgija', '0004_typed_mass_exception_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinissue',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='bulletinissue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='bulletinlayout',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='bulletinlayout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bulletinlayout',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='bulletinlayout',
            name='unified_key',
            field=models.CharField(blank=True, db_index=True, max_length=512),
        ),
        migrations.AddField(
            model_name='liturgicalcalendarentry',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='liturgicalcalendarentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='liturgicalcalendarentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AddField(
            model_name='liturgicalcalendarimport',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='liturgicaltradition',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='liturgicaltradition',
            name='unified_key',
            field=models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ'),
        ),
        migrations.AddField(
            model_name='massexception',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='massexception',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='massintention',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='massintention',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='massintention',
            name='status',
            field=models.CharField(blank=True, choices=[('requested', 'Zatraženo'), ('scheduled', 'Raspoređeno'), ('fulfilled', 'Ispunjeno'), ('transferred', 'Upućeno'), ('cancelled', 'Otkazano')], db_index=True, default='requested', max_length=20),
        ),
        migrations.AddField(
            model_name='massschedulelogentry',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='massschedulelogentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='massscheduleslot',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='massscheduleslot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='massscheduleslot',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno'),
        ),
        migrations.AddField(
            model_name='massscheduleslot',
            name='unified_key',
            field=models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ'),
        ),
        migrations.AlterField(
            model_name='bulletinissue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AlterField(
            model_name='liturgicalcalendarentry',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='liturgicalcalendarimport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='liturgicalcalendarimport',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='liturgicaltradition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='liturgicaltradition',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno'),
        ),
        migrations.AlterField(
            model_name='massexception',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AlterField(
            model_name='massintention',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AlterField(
            model_name='massschedulelogentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AlterField(
            model_name='massscheduleslot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
    ]
