# Generated by Django 5.2.16 on 2026-09-21 08:23

import datetime
import django.utils.timezone
import pastoral.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diocese',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('is_active', models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Biskupija',
                'verbose_name_plural': 'Biskupije',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True, default=pastoral.models.otp_challenge_expiry)),
                ('used', models.BooleanField(default=False)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(default='bdm-slavonski-brod', unique=True)),
                ('canonical_tradition', models.CharField(choices=[('latin', 'Latinska'), ('eastern', 'Istočna')], db_index=True, default='latin', help_text='Latinska za hrvatske biskupije; istočna za župe Križevačke eparhije.', max_length=16, verbose_name='Kanonska tradicija')),
                ('lifecycle_status', models.CharField(choices=[('provisioning', 'Provisioning'), ('active', 'Aktivno'), ('suspended', 'Suspendirano'), ('offboarding', 'Offboarding'), ('archived', 'Arhivirano')], db_index=True, default='active', max_length=20)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktivno')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Župa',
                'verbose_name_plural': 'Župe',
            },
        ),
        migrations.CreateModel(
            name='ParishMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('date_from', models.DateField(default=datetime.date.today, verbose_name='Vrijedi od')),
                ('date_to', models.DateField(db_index=True, default=datetime.date(9999, 12, 31), verbose_name='Vrijedi do')),
                ('role', models.CharField(choices=[('zupnik', 'Župnik'), ('vikar', 'Župnik suradnik / vikar'), ('upravitelj', 'Župni upravitelj'), ('ured', 'Župni ured'), ('financije', 'Financije'), ('revizor', 'Revizor'), ('biskupija', 'Biskupijski preglednik')], max_length=24)),
                ('status', models.CharField(choices=[('active', 'Aktivno'), ('suspended', 'Suspendirano'), ('revoked', 'Opozvano')], db_index=True, default='active', max_length=16)),
                ('permission_set', models.JSONField(blank=True, default=dict)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Članstvo u župi',
                'verbose_name_plural': 'Članstva u župama',
                'ordering': ('parish', 'user__email'),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('role', models.CharField(choices=[('zupnik', 'Župnik'), ('vikar', 'Vikar'), ('upravitelj', 'Župni upravitelj')], default='zupnik', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_staff', models.BooleanField(db_index=True, default=False)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('unified_key', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users_user',
            },
        ),
    ]
