# Generated by Django 5.2.16 on 2026-08-03 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0001_initial'),
        ('pastoral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parish',
            name='diocese',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parishes', to='control_plane.diocese'),
        ),
        migrations.AddField(
            model_name='parish',
            name='lifecycle_status',
            field=models.CharField(choices=[('provisioning', 'Provisioning'), ('active', 'Aktivno'), ('suspended', 'Suspendirano'), ('offboarding', 'Offboarding'), ('archived', 'Arhivirano')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='parish',
            name='tenant_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
