# Generated by Django 5.2.16 on 2026-09-21 08:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('liturgija', '0001_initial'),
        ('pastoral', '0001_initial'),
        ('zupa_vjernici', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parish',
            name='default_liturgical_tradition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parishes', to='liturgija.liturgicaltradition', verbose_name='Zadana liturgijska tradicija'),
        ),
        migrations.AddField(
            model_name='parish',
            name='diocese',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parishes', to='pastoral.diocese'),
        ),
        migrations.AddField(
            model_name='parish',
            name='ecclesiastical_jurisdiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parishes', to='zupa_vjernici.ecclesiasticaljurisdiction', verbose_name='Crkvena jurisdikcija'),
        ),
        migrations.AddField(
            model_name='parishmembership',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_parish_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parishmembership',
            name='parish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='pastoral.parish'),
        ),
        migrations.AddField(
            model_name='parishmembership',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_parish_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parishmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parish_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='parishmembership',
            index=models.Index(fields=['parish', 'status'], name='control_mem_parish_status'),
        ),
        migrations.AddIndex(
            model_name='parishmembership',
            index=models.Index(fields=['user', 'status'], name='control_mem_user_status'),
        ),
        migrations.AddConstraint(
            model_name='parishmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('date_to', datetime.date(9999, 12, 31))), fields=('parish', 'user'), name='control_unique_parish_user_membership'),
        ),
        migrations.AddConstraint(
            model_name='parishmembership',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='control_membership_valid_period'),
        ),
    ]
