# Generated by Django 5.2.16 on 2026-08-03 11:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0003_assign_unique_tenant_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parish',
            name='tenant_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
