# Generated by Django 5.2.5 on 2026-08-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0004_alter_parish_tenant_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiturgicalCalendarImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Godina')),
                ('provider', models.CharField(choices=[('litcal-va', 'LitCal — opći rimski kalendar')], default='litcal-va', max_length=30, verbose_name='Izvor')),
                ('events', models.JSONField(default=list, editable=False, verbose_name='Uvezeni događaji')),
                ('event_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Broj događaja')),
                ('source_file_name', models.CharField(blank=True, editable=False, max_length=255, verbose_name='Izvorna datoteka')),
                ('checksum', models.CharField(blank=True, editable=False, max_length=64, verbose_name='SHA-256 kontrolni zbroj')),
                ('imported_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Vrijeme uvoza')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('imported_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liturgical_calendar_imports', to=settings.AUTH_USER_MODEL, verbose_name='Uvezao')),
            ],
            options={
                'verbose_name': 'Uvoz liturgijskog kalendara',
                'verbose_name_plural': 'Uvozi liturgijskog kalendara',
                'ordering': ['-year', 'provider'],
                'constraints': [models.UniqueConstraint(fields=('year', 'provider'), name='unique_liturgical_calendar_import')],
            },
        ),
    ]
