# Generated by Django 5.2.5 on 2026-08-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0005_liturgicalcalendarimport'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiturgicalCalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Datum')),
                ('name', models.CharField(max_length=255, verbose_name='Svetac ili slavlje')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Izvorni naziv')),
                ('liturgical_color', models.CharField(choices=[('white', 'Bijela'), ('red', 'Crvena'), ('green', 'Zelena'), ('purple', 'Ljubičasta'), ('rose', 'Ružičasta'), ('black', 'Crna'), ('other', 'Druga / nepoznata')], db_index=True, default='other', max_length=20, verbose_name='Liturgijska boja')),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='LitCal stupanj slavlja; veći broj znači viši prioritet.', verbose_name='Prioritet')),
                ('priority_label', models.CharField(blank=True, max_length=120, verbose_name='Naziv prioriteta')),
                ('is_primary', models.BooleanField(db_index=True, default=False, verbose_name='Glavno slavlje dana')),
                ('external_identifier', models.CharField(blank=True, max_length=160, verbose_name='Identifikator izvora')),
                ('source_position', models.PositiveIntegerField(verbose_name='Redni broj u importu')),
                ('raw_data', models.JSONField(default=dict, editable=False, verbose_name='Izvorni podaci')),
                ('calendar_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='pastoral.liturgicalcalendarimport', verbose_name='Kalendarski import')),
            ],
            options={
                'verbose_name': 'Liturgijski kalendarski zapis',
                'verbose_name_plural': 'Liturgijski kalendarski zapisi',
                'ordering': ['date', '-is_primary', '-priority', 'name'],
                'indexes': [models.Index(fields=['date', 'is_primary'], name='liturgical_date_primary_idx')],
                'constraints': [models.UniqueConstraint(fields=('calendar_import', 'source_position'), name='unique_liturgical_entry_source_position')],
            },
        ),
    ]
