# Generated by Django 5.2.16 on 2026-08-18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0006_liturgicalcalendarentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchSuiIuris',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='Stabilni kod')),
                ('official_name', models.CharField(max_length=200, verbose_name='Službeni naziv')),
                ('short_name', models.CharField(blank=True, max_length=120, verbose_name='Kratki naziv')),
                ('canonical_tradition', models.CharField(choices=[('latin', 'Latinska'), ('eastern', 'Istočna')], db_index=True, max_length=16, verbose_name='Kanonska tradicija')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktivno')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
            ],
            options={
                'verbose_name': 'Crkva sui iuris',
                'verbose_name_plural': 'Crkve sui iuris',
                'ordering': ('official_name',),
            },
        ),
        migrations.CreateModel(
            name='LiturgicalTradition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=50, unique=True, verbose_name='Stabilni kod')),
                ('name', models.CharField(max_length=160, verbose_name='Naziv')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktivno')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
            ],
            options={
                'verbose_name': 'Liturgijska tradicija',
                'verbose_name_plural': 'Liturgijske tradicije',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='parish',
            name='church_sui_iuris',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parishes', to='pastoral.churchsuiiuris', verbose_name='Crkva sui iuris'),
        ),
        migrations.CreateModel(
            name='EcclesiasticalJurisdiction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80, unique=True, verbose_name='Stabilni kod')),
                ('official_name', models.CharField(max_length=220, verbose_name='Službeni naziv')),
                ('jurisdiction_type', models.CharField(choices=[('diocese', 'Biskupija'), ('archdiocese', 'Nadbiskupija'), ('eparchy', 'Eparhija'), ('archeparchy', 'Arhieparhija'), ('other', 'Drugo')], db_index=True, max_length=20, verbose_name='Vrsta jurisdikcije')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktivno')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('church_sui_iuris', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jurisdictions', to='pastoral.churchsuiiuris', verbose_name='Crkva sui iuris')),
                ('parent_jurisdiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_jurisdictions', to='pastoral.ecclesiasticaljurisdiction', verbose_name='Nadređena jurisdikcija')),
            ],
            options={
                'verbose_name': 'Crkvena jurisdikcija',
                'verbose_name_plural': 'Crkvene jurisdikcije',
                'ordering': ('official_name',),
            },
        ),
        migrations.AddField(
            model_name='parish',
            name='ecclesiastical_jurisdiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parishes', to='pastoral.ecclesiasticaljurisdiction', verbose_name='Crkvena jurisdikcija'),
        ),
        migrations.AddField(
            model_name='churchsuiiuris',
            name='default_liturgical_tradition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='churches_sui_iuris', to='pastoral.liturgicaltradition', verbose_name='Zadana liturgijska tradicija'),
        ),
        migrations.AddField(
            model_name='parish',
            name='default_liturgical_tradition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parishes', to='pastoral.liturgicaltradition', verbose_name='Zadana liturgijska tradicija'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('given_names', models.CharField(max_length=160, verbose_name='Ime / imena')),
                ('surname', models.CharField(max_length=160, verbose_name='Prezime')),
                ('birth_surname', models.CharField(blank=True, max_length=160, verbose_name='Rođeno prezime')),
                ('sex', models.CharField(choices=[('female', 'Ženski'), ('male', 'Muški'), ('unknown', 'Nepoznato / nepotvrđeno')], default='unknown', max_length=12, verbose_name='Spol')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Datum rođenja')),
                ('place_of_birth', models.CharField(blank=True, max_length=180, verbose_name='Mjesto rođenja')),
                ('normalized_given_names', models.CharField(db_index=True, editable=False, max_length=160)),
                ('normalized_surname', models.CharField(db_index=True, editable=False, max_length=160)),
                ('status', models.CharField(choices=[('active', 'Aktivna'), ('merged', 'Spojena'), ('archived', 'Arhivirana')], db_index=True, default='active', max_length=12, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_as_father', to='pastoral.person', verbose_name='Otac')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_as_mother', to='pastoral.person', verbose_name='Majka')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persons', to='pastoral.parish', verbose_name='Župa')),
            ],
            options={
                'verbose_name': 'Osoba',
                'verbose_name_plural': 'Osobe',
                'ordering': ('surname', 'given_names', 'date_of_birth'),
            },
        ),
        migrations.CreateModel(
            name='ChurchEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Vrijedi od')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Vrijedi do')),
                ('enrollment_basis', models.CharField(blank=True, max_length=200, verbose_name='Temelj pripadnosti')),
                ('decree_reference', models.CharField(blank=True, max_length=200, verbose_name='Referenca dekreta')),
                ('status', models.CharField(choices=[('unconfirmed', 'Nepotvrđeno'), ('confirmed', 'Potvrđeno')], db_index=True, default='unconfirmed', max_length=12, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='church_enrollments', to='pastoral.parish', verbose_name='Župa')),
                ('previous_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='following_enrollments', to='pastoral.churchenrollment', verbose_name='Prethodna pripadnost')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_church_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Evidentirao')),
                ('church_sui_iuris', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_enrollments', to='pastoral.churchsuiiuris', verbose_name='Crkva sui iuris')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='church_enrollments', to='pastoral.person', verbose_name='Osoba')),
            ],
            options={
                'verbose_name': 'Pripadnost Crkvi sui iuris',
                'verbose_name_plural': 'Pripadnosti Crkvi sui iuris',
                'ordering': ('person', '-valid_from', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='RegistryAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=100, verbose_name='Vrsta događaja')),
                ('target_type', models.CharField(blank=True, max_length=100, verbose_name='Vrsta cilja')),
                ('target_id', models.CharField(blank=True, max_length=100, verbose_name='Identifikator cilja')),
                ('outcome', models.CharField(choices=[('success', 'Uspjeh'), ('denied', 'Odbijeno'), ('failure', 'Greška')], db_index=True, default='success', max_length=16, verbose_name='Ishod')),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('changed_fields', models.JSONField(blank=True, default=list, verbose_name='Promijenjena polja')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metapodaci')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vrijeme')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registry_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Korisnik')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registry_audit_events', to='pastoral.parish', verbose_name='Župa')),
            ],
            options={
                'verbose_name': 'Audit matične evidencije',
                'verbose_name_plural': 'Audit matične evidencije',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['parish', 'normalized_surname', 'normalized_given_names'], name='person_parish_name_lookup'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['parish', 'date_of_birth'], name='person_parish_birth_lookup'),
        ),
        migrations.AddIndex(
            model_name='churchenrollment',
            index=models.Index(fields=['parish', 'status'], name='enrollment_parish_status'),
        ),
        migrations.AddConstraint(
            model_name='churchenrollment',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_from__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='enrollment_valid_period'),
        ),
        migrations.AddConstraint(
            model_name='churchenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed'), ('valid_until__isnull', True)), fields=('person',), name='one_current_confirmed_enrollment'),
        ),
        migrations.AddIndex(
            model_name='registryauditevent',
            index=models.Index(fields=['parish', 'occurred_at'], name='registry_audit_parish_time'),
        ),
        migrations.AddIndex(
            model_name='registryauditevent',
            index=models.Index(fields=['actor', 'occurred_at'], name='registry_audit_actor_time'),
        ),
    ]
