# Generated by Django 5.2.16 on 2026-08-18 14:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0007_church_structure_person_and_registry_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParishRegistryConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relational_baptisms_enabled', models.BooleanField(default=False, help_text='Uključuje se tek nakon provjere migriranih zapisa.', verbose_name='Relacijski prikaz krštenja uključen')),
                ('baptism_backfill_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Migracija krštenja završena')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('parish', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='registry_configuration', to='pastoral.parish', verbose_name='Župa')),
            ],
            options={
                'verbose_name': 'Postavke matičnih evidencija župe',
                'verbose_name_plural': 'Postavke matičnih evidencija župa',
            },
        ),
        migrations.CreateModel(
            name='RegisterBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=220, verbose_name='Naziv')),
                ('volume', models.CharField(blank=True, max_length=80, verbose_name='Svezak')),
                ('year_from', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Od godine')),
                ('year_until', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Do godine')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Mjesto čuvanja')),
                ('custodian', models.CharField(blank=True, max_length=200, verbose_name='Odgovorna osoba')),
                ('status', models.CharField(choices=[('draft', 'Nacrt'), ('active', 'Aktivna'), ('locked', 'Zaključana'), ('archived', 'Arhivirana')], db_index=True, default='draft', max_length=12, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register_books', to='pastoral.parish', verbose_name='Župa')),
            ],
            options={
                'verbose_name': 'Matična knjiga',
                'verbose_name_plural': 'Matične knjige',
                'ordering': ('parish', 'title'),
            },
        ),
        migrations.CreateModel(
            name='RegisterBookYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(verbose_name='Godina')),
                ('status', models.CharField(choices=[('open', 'Otvorena'), ('locked', 'Zaključana'), ('archived', 'Arhivirana')], default='open', max_length=12, verbose_name='Status')),
                ('next_entry_number', models.PositiveIntegerField(default=1, verbose_name='Sljedeći redni broj')),
                ('register_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='years', to='pastoral.registerbook', verbose_name='Matična knjiga')),
            ],
            options={
                'verbose_name': 'Godina matične knjige',
                'verbose_name_plural': 'Godine matičnih knjiga',
                'ordering': ('register_book', '-year'),
            },
        ),
        migrations.CreateModel(
            name='RegisterTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='Stabilni kod')),
                ('event_type', models.CharField(choices=[('baptism', 'Krštenje'), ('first_communion', 'Prva pričest'), ('confirmation', 'Krizma'), ('marriage', 'Vjenčanje'), ('anointing', 'Pomazanje'), ('funeral', 'Sprovod')], max_length=24, verbose_name='Vrsta sakramenta')),
                ('name', models.CharField(max_length=220, verbose_name='Naziv')),
                ('owner_scope', models.CharField(choices=[('system', 'Sustav'), ('church', 'Crkva sui iuris'), ('jurisdiction', 'Crkvena jurisdikcija')], default='system', max_length=16, verbose_name='Vlasnik')),
                ('is_official', models.BooleanField(default=False, verbose_name='Službeni obrazac')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Aktivno')),
                ('church_sui_iuris', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='register_templates', to='pastoral.churchsuiiuris', verbose_name='Crkva sui iuris')),
                ('ecclesiastical_jurisdiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='register_templates', to='pastoral.ecclesiasticaljurisdiction', verbose_name='Crkvena jurisdikcija')),
            ],
            options={
                'verbose_name': 'Predložak matične knjige',
                'verbose_name_plural': 'Predlošci matičnih knjiga',
                'ordering': ('event_type', 'name'),
            },
        ),
        migrations.CreateModel(
            name='RegisterTemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveSmallIntegerField(verbose_name='Verzija')),
                ('status', models.CharField(choices=[('draft', 'Nacrt'), ('published', 'Objavljeno'), ('retired', 'Povučeno')], default='draft', max_length=12, verbose_name='Status')),
                ('field_schema', models.JSONField(blank=True, default=list, verbose_name='Definicije polja')),
                ('validation_schema', models.JSONField(blank=True, default=dict, verbose_name='Pravila validacije')),
                ('terminology', models.JSONField(blank=True, default=dict, verbose_name='Terminologija')),
                ('print_configuration', models.JSONField(blank=True, default=dict, verbose_name='Postavke ispisa')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='Vrijedi od')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Objavljeno')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_register_template_versions', to=settings.AUTH_USER_MODEL, verbose_name='Objavio')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='pastoral.registertemplate', verbose_name='Predložak')),
            ],
            options={
                'verbose_name': 'Verzija predloška matične knjige',
                'verbose_name_plural': 'Verzije predložaka matičnih knjiga',
                'ordering': ('template', '-version_number'),
            },
        ),
        migrations.AddField(
            model_name='registerbook',
            name='template_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register_books', to='pastoral.registertemplateversion', verbose_name='Verzija predloška'),
        ),
        migrations.CreateModel(
            name='SacramentalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('baptism', 'Krštenje'), ('first_communion', 'Prva pričest'), ('confirmation', 'Krizma'), ('marriage', 'Vjenčanje'), ('anointing', 'Pomazanje'), ('funeral', 'Sprovod')], db_index=True, max_length=24, verbose_name='Vrsta sakramenta')),
                ('event_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Datum')),
                ('place_name', models.CharField(blank=True, max_length=200, verbose_name='Mjesto')),
                ('minister_name', models.CharField(blank=True, max_length=200, verbose_name='Povijesni naziv služitelja')),
                ('canonical_tradition', models.CharField(choices=[('latin', 'Latinska'), ('eastern', 'Istočna'), ('unconfirmed', 'Nepotvrđeno')], default='unconfirmed', max_length=16, verbose_name='Kanonska tradicija')),
                ('status', models.CharField(choices=[('draft', 'Nacrt'), ('confirmed', 'Potvrđeno'), ('locked', 'Zaključano'), ('corrected', 'Ispravljeno'), ('cancelled', 'Poništeno'), ('legacy_imported', 'Uvezeno iz postojećeg sustava')], db_index=True, default='draft', max_length=24, verbose_name='Status')),
                ('source', models.CharField(choices=[('manual', 'Ručni unos'), ('public_submission', 'Javna prijava'), ('legacy_import', 'Postojeći sustav')], db_index=True, default='manual', max_length=24, verbose_name='Izvor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('celebrating_parish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='celebrated_sacramental_events', to='pastoral.parish', verbose_name='Župa slavlja')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_sacramental_events', to=settings.AUTH_USER_MODEL, verbose_name='Kreirao')),
                ('liturgical_tradition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sacramental_events', to='pastoral.liturgicaltradition', verbose_name='Liturgijska tradicija')),
                ('minister', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ministered_sacramental_events', to=settings.AUTH_USER_MODEL, verbose_name='Služitelj')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sacramental_events', to='pastoral.parish', verbose_name='Župa')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_sacramental_events', to=settings.AUTH_USER_MODEL, verbose_name='Ažurirao')),
            ],
            options={
                'verbose_name': 'Sakramentalni događaj',
                'verbose_name_plural': 'Sakramentalni događaji',
                'ordering': ('-event_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='RegisterEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Redni broj')),
                ('entry_reference', models.CharField(blank=True, max_length=100, verbose_name='Izvorna oznaka zapisa')),
                ('page_number', models.CharField(blank=True, max_length=40, verbose_name='Stranica')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Datum upisa')),
                ('status', models.CharField(choices=[('draft', 'Nacrt'), ('confirmed', 'Potvrđeno'), ('locked', 'Zaključano'), ('corrected', 'Ispravljeno'), ('cancelled', 'Poništeno'), ('legacy_imported', 'Uvezeno iz postojećeg sustava')], db_index=True, default='draft', max_length=24, verbose_name='Status')),
                ('custom_values', models.JSONField(blank=True, default=dict, verbose_name='Dodatna polja predloška')),
                ('correction_reason', models.TextField(blank=True, verbose_name='Razlog ispravka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_register_entries', to=settings.AUTH_USER_MODEL, verbose_name='Kreirao')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register_entries', to='pastoral.parish', verbose_name='Župa')),
                ('previous_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_entries', to='pastoral.registerentry', verbose_name='Prethodni zapis')),
                ('register_book_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='pastoral.registerbookyear', verbose_name='Godina knjige')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_register_entries', to=settings.AUTH_USER_MODEL, verbose_name='Ažurirao')),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register_entries', to='pastoral.registertemplateversion', verbose_name='Verzija predloška')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='register_entry', to='pastoral.sacramentalevent', verbose_name='Događaj')),
            ],
            options={
                'verbose_name': 'Zapis matične knjige',
                'verbose_name_plural': 'Zapisi matičnih knjiga',
                'ordering': ('register_book_year', 'entry_number', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='LegacyRecordLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_collection', models.CharField(max_length=80, verbose_name='Izvorna zbirka')),
                ('source_identifier', models.CharField(max_length=160, verbose_name='Izvorni identifikator')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_record_links', to='pastoral.parish', verbose_name='Župa')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_record_links', to='pastoral.person', verbose_name='Osoba')),
                ('register_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_record_links', to='pastoral.registerbook', verbose_name='Matična knjiga')),
                ('register_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_record_links', to='pastoral.registerentry', verbose_name='Zapis matične knjige')),
                ('sacramental_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_record_links', to='pastoral.sacramentalevent', verbose_name='Sakramentalni događaj')),
            ],
            options={
                'verbose_name': 'Veza sa starim zapisom',
                'verbose_name_plural': 'Veze sa starim zapisima',
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('recipient', 'Primatelj'), ('parent', 'Roditelj'), ('godparent', 'Kum / kuma'), ('spouse', 'Zaručnik / zaručnica'), ('witness', 'Svjedok')], db_index=True, max_length=20, verbose_name='Uloga')),
                ('historical_name', models.CharField(blank=True, help_text='Čuva izvorni tekst kada osobe nije sigurno automatski razdvojiti.', max_length=300, verbose_name='Povijesni zapis imena')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Redoslijed prikaza')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sacramental_event_participants', to='pastoral.parish', verbose_name='Župa')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sacramental_participations', to='pastoral.person', verbose_name='Osoba')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='pastoral.sacramentalevent', verbose_name='Događaj')),
            ],
            options={
                'verbose_name': 'Sudionik sakramentalnog događaja',
                'verbose_name_plural': 'Sudionici sakramentalnih događaja',
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BaptismDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godparent_certificate_received', models.BooleanField(default=False, verbose_name='Zaprimljena potvrda za kuma')),
                ('legacy_operational_data', models.JSONField(blank=True, default=dict, help_text='Samo podaci bez sigurnog relacijskog polja; nije glavni zapis sakramenta.', verbose_name='Sačuvani operativni podaci starog sustava')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='baptism_details', to='pastoral.sacramentalevent', verbose_name='Krštenje')),
            ],
            options={
                'verbose_name': 'Podaci o krštenju',
                'verbose_name_plural': 'Podaci o krštenjima',
            },
        ),
        migrations.AddConstraint(
            model_name='registerbookyear',
            constraint=models.UniqueConstraint(fields=('register_book', 'year'), name='unique_register_book_year'),
        ),
        migrations.AddConstraint(
            model_name='registertemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version_number'), name='unique_register_template_version'),
        ),
        migrations.AddIndex(
            model_name='registerbook',
            index=models.Index(fields=['parish', 'status'], name='book_parish_status'),
        ),
        migrations.AddIndex(
            model_name='sacramentalevent',
            index=models.Index(fields=['parish', 'event_type', 'event_date'], name='event_parish_type_date'),
        ),
        migrations.AddIndex(
            model_name='sacramentalevent',
            index=models.Index(fields=['parish', 'status'], name='event_parish_status'),
        ),
        migrations.AddIndex(
            model_name='registerentry',
            index=models.Index(fields=['parish', 'status'], name='entry_parish_status'),
        ),
        migrations.AddConstraint(
            model_name='registerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_number__isnull', False)), fields=('register_book_year', 'entry_number'), name='unique_number_in_register_book_year'),
        ),
        migrations.AddIndex(
            model_name='legacyrecordlink',
            index=models.Index(fields=['parish', 'source_collection'], name='legacy_link_parish_collection'),
        ),
        migrations.AddConstraint(
            model_name='legacyrecordlink',
            constraint=models.UniqueConstraint(fields=('parish', 'source_collection', 'source_identifier'), name='unique_legacy_record_link'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['parish', 'role'], name='participant_parish_role'),
        ),
        migrations.AddConstraint(
            model_name='eventparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('person__isnull', False), models.Q(('historical_name', ''), _negated=True), _connector='OR'), name='participant_has_person_or_name'),
        ),
    ]
