# Generated by Django 5.2.16 on 2026-08-18 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0008_parishregistryconfiguration_registerbook_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='baptismdetails',
            name='operational_status',
            field=models.CharField(db_index=True, default='upis', max_length=40, verbose_name='Operativni status'),
        ),
        migrations.AddField(
            model_name='baptismdetails',
            name='stipend',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prilog'),
        ),
        migrations.AddField(
            model_name='baptismdetails',
            name='stipend_paid',
            field=models.BooleanField(default=False, verbose_name='Prilog evidentiran'),
        ),
        migrations.AddField(
            model_name='sacramentalevent',
            name='public_identifier',
            field=models.CharField(blank=True, help_text='Stabilni identifikator koji koriste URL-ovi i korisničko sučelje.', max_length=160, verbose_name='Stabilni identifikator'),
        ),
        migrations.AddConstraint(
            model_name='sacramentalevent',
            constraint=models.UniqueConstraint(condition=models.Q(('public_identifier', ''), _negated=True), fields=('parish', 'event_type', 'public_identifier'), name='unique_event_public_identifier'),
        ),
    ]
