# Generated by Django 5.2.16 on 2026-08-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0010_cutover_baptisms_to_relational'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parishregistryconfiguration',
            name='parish',
        ),
        migrations.RemoveField(
            model_name='baptismdetails',
            name='legacy_operational_data',
        ),
        migrations.DeleteModel(
            name='LegacyRecordLink',
        ),
        migrations.DeleteModel(
            name='ParishRegistryConfiguration',
        ),
    ]
