# Generated by Django 5.2.16 on 2026-08-19 06:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0011_remove_parishregistryconfiguration_parish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationProgramYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('program_type', models.CharField(choices=[('first_communion', 'Prva pričest'), ('confirmation', 'Krizma')], db_index=True, max_length=24, verbose_name='Vrsta priprave')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Godina')),
                ('group_name', models.CharField(blank=True, max_length=160, verbose_name='Naziv skupine')),
                ('ceremony_date', models.DateField(blank=True, null=True, verbose_name='Datum slavlja')),
                ('celebrant_name', models.CharField(blank=True, max_length=200, verbose_name='Slavitelj')),
                ('contribution_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zajednički prilog')),
                ('contribution_paid', models.BooleanField(default=False, verbose_name='Prilog evidentiran')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formation_program_years', to='pastoral.parish', verbose_name='Župa')),
            ],
            options={
                'verbose_name': 'Godina sakramentalne priprave',
                'verbose_name_plural': 'Godine sakramentalne priprave',
                'ordering': ('program_type', '-year'),
            },
        ),
        migrations.CreateModel(
            name='FormationCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_identifier', models.CharField(max_length=160, verbose_name='Stabilni identifikator')),
                ('historical_name', models.CharField(max_length=220, verbose_name='Ime i prezime')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Datum rođenja')),
                ('school_name', models.CharField(blank=True, max_length=200, verbose_name='Škola')),
                ('school_class', models.CharField(blank=True, max_length=40, verbose_name='Razred')),
                ('group_name', models.CharField(blank=True, max_length=80, verbose_name='Skupina')),
                ('parents_name', models.CharField(blank=True, max_length=300, verbose_name='Roditelji')),
                ('sponsor_name', models.CharField(blank=True, max_length=220, verbose_name='Kum / kuma')),
                ('baptism_date', models.DateField(blank=True, null=True, verbose_name='Datum krštenja')),
                ('operational_status', models.CharField(default='upis', max_length=40, verbose_name='Status')),
                ('contribution_paid', models.BooleanField(default=False, verbose_name='Prilog evidentiran')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formation_candidates', to='pastoral.person', verbose_name='Osoba')),
                ('program_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='pastoral.formationprogramyear', verbose_name='Godina priprave')),
            ],
            options={
                'verbose_name': 'Kandidat sakramentalne priprave',
                'verbose_name_plural': 'Kandidati sakramentalne priprave',
                'ordering': ('historical_name',),
            },
        ),
        migrations.AddConstraint(
            model_name='formationprogramyear',
            constraint=models.UniqueConstraint(fields=('parish', 'program_type', 'year'), name='unique_formation_program_year'),
        ),
        migrations.AddConstraint(
            model_name='formationcandidate',
            constraint=models.UniqueConstraint(fields=('program_year', 'public_identifier'), name='unique_candidate_in_program_year'),
        ),
    ]
