# Generated by Django 5.2.16 on 2026-08-19 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0012_formationprogramyear_formationcandidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationcandidate',
            name='given_names',
            field=models.CharField(blank=True, max_length=160, verbose_name='Ime / imena'),
        ),
        migrations.AddField(
            model_name='formationcandidate',
            name='surname',
            field=models.CharField(blank=True, max_length=160, verbose_name='Prezime'),
        ),
        migrations.AddField(
            model_name='formationprogramyear',
            name='contribution_paid_at',
            field=models.DateField(blank=True, null=True, verbose_name='Datum evidencije priloga'),
        ),
        migrations.AddField(
            model_name='formationprogramyear',
            name='public_identifier',
            field=models.CharField(default=uuid.uuid4, help_text='Identifikator koji koriste postojeći URL-ovi i korisničko sučelje.', max_length=160, verbose_name='Stabilni identifikator'),
        ),
        migrations.AddConstraint(
            model_name='formationprogramyear',
            constraint=models.UniqueConstraint(fields=('parish', 'program_type', 'public_identifier'), name='unique_formation_program_identifier'),
        ),
    ]
