# Generated by Django 5.2.16 on 2026-08-19 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0014_cutover_formation_programs_to_relational'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarriageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couple_display_name', models.CharField(max_length=320, verbose_name='Mladenci')),
                ('contact', models.CharField(blank=True, max_length=160, verbose_name='Kontakt')),
                ('preparatory_sessions', models.PositiveSmallIntegerField(default=0, verbose_name='Broj susreta priprave')),
                ('documents_complete', models.BooleanField(default=False, verbose_name='Dokumenti potpuni')),
                ('witnesses_name', models.CharField(blank=True, max_length=400, verbose_name='Svjedoci')),
                ('operational_status', models.CharField(db_index=True, default='planirano', max_length=40, verbose_name='Operativni status')),
                ('stipend', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stipendij')),
                ('stipend_paid', models.BooleanField(default=False, verbose_name='Stipendij evidentiran')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='marriage_details', to='pastoral.sacramentalevent', verbose_name='Vjenčanje')),
            ],
            options={
                'verbose_name': 'Podaci o vjenčanju',
                'verbose_name_plural': 'Podaci o vjenčanjima',
            },
        ),
    ]
