# Generated by Django 5.2.16 on 2026-08-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0016_cutover_weddings_to_relational'),
    ]

    operations = [
        migrations.AddField(
            model_name='marriagedetails',
            name='bride_witness_name',
            field=models.CharField(blank=True, max_length=220, verbose_name='Svjedok zaručnice'),
        ),
        migrations.AddField(
            model_name='marriagedetails',
            name='groom_witness_name',
            field=models.CharField(blank=True, max_length=220, verbose_name='Svjedok zaručnika'),
        ),
    ]
