# Generated by Django 5.2.16 on 2026-08-19 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0017_marriagedetails_bride_witness_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuneralDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Datum smrti')),
                ('cemetery_location', models.CharField(blank=True, max_length=240, verbose_name='Adresa / lokacija groblja')),
                ('family_contact', models.CharField(blank=True, max_length=240, verbose_name='Kontakt obitelji')),
                ('mass_planned', models.BooleanField(default=False, verbose_name='Misa zadušnica planirana')),
                ('mass_date', models.DateField(blank=True, null=True, verbose_name='Datum mise zadušnice')),
                ('mass_time', models.TimeField(blank=True, null=True, verbose_name='Vrijeme mise zadušnice')),
                ('operational_status', models.CharField(db_index=True, default='planirano', max_length=40, verbose_name='Operativni status')),
                ('stipend', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stipendij')),
                ('stipend_paid', models.BooleanField(default=False, verbose_name='Stipendij evidentiran')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='funeral_details', to='pastoral.sacramentalevent', verbose_name='Pogreb')),
            ],
            options={
                'verbose_name': 'Podaci o pogrebu',
                'verbose_name_plural': 'Podaci o pogrebima',
            },
        ),
    ]
