# Generated by Django 5.2.16 on 2026-08-19 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0019_cutover_funerals_to_relational'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnointingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.TimeField(blank=True, null=True, verbose_name='Vrijeme')),
                ('address', models.CharField(blank=True, max_length=240, verbose_name='Adresa / ustanova')),
                ('location', models.CharField(blank=True, max_length=240, verbose_name='Detalj lokacije')),
                ('contact', models.CharField(blank=True, max_length=240, verbose_name='Kontakt')),
                ('notes', models.TextField(blank=True, verbose_name='Napomena')),
                ('operational_status', models.CharField(db_index=True, default='planirano', max_length=40, verbose_name='Operativni status')),
                ('completed', models.BooleanField(default=False, verbose_name='Obavljeno')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='anointing_details', to='pastoral.sacramentalevent', verbose_name='Pomazanje')),
            ],
            options={
                'verbose_name': 'Podaci o pomazanju',
                'verbose_name_plural': 'Podaci o pomazanjima',
            },
        ),
    ]
