# Generated by Django 5.2.16 on 2026-08-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0021_cutover_anointings_to_relational'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerbook',
            name='last_entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Zadnji unos'),
        ),
        migrations.AddField(
            model_name='registerbook',
            name='last_entry_reference',
            field=models.CharField(blank=True, max_length=80, verbose_name='Zadnji broj'),
        ),
        migrations.AddField(
            model_name='registerbook',
            name='operational_status',
            field=models.CharField(blank=True, max_length=80, verbose_name='Opis statusa'),
        ),
        migrations.AddField(
            model_name='registerbook',
            name='public_identifier',
            field=models.CharField(blank=True, max_length=160, verbose_name='Stabilni identifikator'),
        ),
        migrations.AddField(
            model_name='registerbook',
            name='registry_type',
            field=models.CharField(choices=[('krštenja', 'Krštenja'), ('vjenčanja', 'Vjenčanja'), ('umrli', 'Umrli'), ('krizma', 'Krizma'), ('ostalo', 'Ostalo')], default='ostalo', max_length=20, verbose_name='Vrsta knjige'),
        ),
        migrations.AddConstraint(
            model_name='registerbook',
            constraint=models.UniqueConstraint(condition=models.Q(('public_identifier', ''), _negated=True), fields=('parish', 'public_identifier'), name='unique_register_book_public_identifier'),
        ),
    ]
