# Generated by Django 5.2.16 on 2026-08-19 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0022_registerbook_last_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerbook',
            name='template_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='register_books', to='pastoral.registertemplateversion', verbose_name='Verzija predloška'),
        ),
    ]
