# Generated by Django 5.2.16 on 2026-08-19 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0024_cutover_register_books_to_relational'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationcandidate',
            name='sacramental_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formation_candidate', to='pastoral.sacramentalevent', verbose_name='Potvrđeni sakramentalni događaj'),
        ),
    ]
