# Generated by Django 5.2.16 on 2026-08-19 07:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0025_formationcandidate_sacramental_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralRegisterEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_identifier', models.CharField(max_length=160, verbose_name='Stabilni identifikator')),
                ('registry_reference', models.CharField(blank=True, max_length=100, verbose_name='Matični broj')),
                ('subject_name', models.CharField(max_length=240, verbose_name='Osoba / zapis')),
                ('record_date', models.DateField(verbose_name='Datum zapisa')),
                ('place', models.CharField(blank=True, max_length=240, verbose_name='Mjesto / napomena')),
                ('responsible_name', models.CharField(blank=True, max_length=200, verbose_name='Odgovorna osoba')),
                ('operational_status', models.CharField(db_index=True, default='upisano', max_length=60, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('register_book_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='general_entries', to='pastoral.registerbookyear', verbose_name='Godina knjige')),
            ],
            options={
                'verbose_name': 'Opći zapis matične knjige',
                'verbose_name_plural': 'Opći zapisi matične knjige',
                'ordering': ('register_book_year', 'record_date', 'created_at'),
                'constraints': [models.UniqueConstraint(fields=('register_book_year', 'public_identifier'), name='unique_general_entry_identifier')],
            },
        ),
    ]
