# Generated by Django 5.2.16 on 2026-08-21 11:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0030_move_domain_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseTwoRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collection_key', models.CharField(db_index=True, max_length=80)),
                ('public_identifier', models.CharField(blank=True, db_index=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_two_records', to='pastoral.parish')),
            ],
            options={
                'indexes': [models.Index(fields=['parish', 'collection_key'], name='pastoral_ph_parish__e55e3d_idx')],
                'unique_together': {('parish', 'collection_key', 'public_identifier')},
            },
        ),
    ]
