# Generated by Django 5.2.16 on 2026-09-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0034_user_db_table_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='diocese',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='parishmembership',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AlterField(
            model_name='diocese',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='diocese',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AlterField(
            model_name='parishmembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='parishmembership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
    ]
