# Generated by Django 5.2.16 on 2026-09-18 09:00

import datetime
from django.db import migrations, models


def _copy_diocese_active(apps, schema_editor):
    Diocese = apps.get_model('pastoral', 'Diocese')
    for diocese in Diocese.objects.all().iterator():
        diocese.is_active = diocese.active
        diocese.save(update_fields=['is_active'])


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0035_fcta_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='diocese',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Aktivno'), (False, 'Neaktivno')], db_index=True, default=True, verbose_name='Aktivno'),
        ),
        migrations.RunPython(_copy_diocese_active, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='diocese',
            name='active',
        ),
        migrations.AddField(
            model_name='diocese',
            name='unified_key',
            field=models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ'),
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='parish',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='parish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='parish',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Aktivno'),
        ),
        migrations.AddField(
            model_name='parish',
            name='unified_key',
            field=models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ'),
        ),
        migrations.AddField(
            model_name='parishmembership',
            name='date_from',
            field=models.DateField(default=datetime.date.today, verbose_name='Vrijedi od'),
        ),
        migrations.AddField(
            model_name='parishmembership',
            name='date_to',
            field=models.DateField(db_index=True, default=datetime.date(9999, 12, 31), verbose_name='Vrijedi do'),
        ),
        migrations.AddField(
            model_name='parishmembership',
            name='unified_key',
            field=models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ'),
        ),
        migrations.AddField(
            model_name='phasetworecord',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='phasetworecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='user',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name='Sadržajni hash'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AddField(
            model_name='user',
            name='unified_key',
            field=models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Jedinstveni ključ'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AlterField(
            model_name='diocese',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='parishmembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='phasetworecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
    ]
