# Generated by Django 5.2.16 on 2026-09-18 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral', '0036_scd_fact_bases'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhaseTwoRecord',
        ),
    ]
